"""
Update Bible books with meaningful key verses for all chapters.
"""

import json
import os

# Comprehensive key verses for all Bible books
COMPREHENSIVE_VERSES = {
    "1 Samuel": {
        1: [{"verse": 27, "text": "For this child I prayed; and the LORD hath given me my petition which I asked of him."}],
        2: [{"verse": 2, "text": "There is none holy as the LORD: for there is none beside thee: neither is there any rock like our God."},
            {"verse": 30, "text": "Them that honour me I will honour, and they that despise me shall be lightly esteemed."}],
        3: [{"verse": 9, "text": "Speak, LORD; for thy servant heareth."},
            {"verse": 10, "text": "And the LORD came, and stood, and called as at other times, Samuel, Samuel. Then Samuel answered, Speak; for thy servant heareth."}],
        4: [{"verse": 21, "text": "And she named the child Ichabod, saying, The glory is departed from Israel."}],
        5: [{"verse": 4, "text": "And when they arose early on the morrow morning, behold, Dagon was fallen upon his face to the ground before the ark of the LORD."}],
        6: [{"verse": 20, "text": "Who is able to stand before this holy LORD God?"}],
        7: [{"verse": 3, "text": "If ye do return unto the LORD with all your hearts, then put away the strange gods."},
            {"verse": 12, "text": "Then Samuel took a stone, and set it between Mizpeh and Shen, and called the name of it Ebenezer, saying, Hitherto hath the LORD helped us."}],
        8: [{"verse": 7, "text": "They have not rejected thee, but they have rejected me, that I should not reign over them."}],
        9: [{"verse": 17, "text": "Behold the man whom I spake to thee of! this same shall reign over my people."}],
        10: [{"verse": 24, "text": "And all the people shouted, and said, God save the king."}],
        11: [{"verse": 13, "text": "To day the LORD hath wrought salvation in Israel."}],
        12: [{"verse": 22, "text": "For the LORD will not forsake his people for his great name's sake: because it hath pleased the LORD to make you his people."},
             {"verse": 24, "text": "Only fear the LORD, and serve him in truth with all your heart: for consider how great things he hath done for you."}],
        13: [{"verse": 14, "text": "But now thy kingdom shall not continue: the LORD hath sought him a man after his own heart."}],
        14: [{"verse": 6, "text": "There is no restraint to the LORD to save by many or by few."},
             {"verse": 45, "text": "God forbid: as the LORD liveth, there shall not one hair of his head fall to the ground; for he hath wrought with God this day."}],
        15: [{"verse": 22, "text": "Hath the LORD as great delight in burnt offerings and sacrifices, as in obeying the voice of the LORD? Behold, to obey is better than sacrifice, and to hearken than the fat of rams."},
             {"verse": 23, "text": "For rebellion is as the sin of witchcraft, and stubbornness is as iniquity and idolatry."}],
        16: [{"verse": 7, "text": "Look not on his countenance, or on the height of his stature; because I have refused him: for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart."},
             {"verse": 13, "text": "Then Samuel took the horn of oil, and anointed him in the midst of his brethren: and the Spirit of the LORD came upon David from that day forward."}],
        17: [{"verse": 45, "text": "Thou comest to me with a sword, and with a spear, and with a shield: but I come to thee in the name of the LORD of hosts, the God of the armies of Israel."},
             {"verse": 47, "text": "And all this assembly shall know that the LORD saveth not with sword and spear: for the battle is the LORD's, and he will give you into our hands."}],
        18: [{"verse": 1, "text": "The soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul."},
             {"verse": 14, "text": "And David behaved himself wisely in all his ways; and the LORD was with him."}],
        19: [{"verse": 5, "text": "For he did put his life in his hand, and slew the Philistine, and the LORD wrought a great salvation for all Israel."}],
        20: [{"verse": 17, "text": "And Jonathan caused David to swear again, because he loved him: for he loved him as he loved his own soul."},
             {"verse": 42, "text": "The LORD be between me and thee, and between my seed and thy seed for ever."}],
        21: [{"verse": 9, "text": "There is none like it; give it me."}],
        22: [{"verse": 23, "text": "Abide thou with me, fear not: for he that seeketh my life seeketh thy life: but with me thou shalt be in safeguard."}],
        23: [{"verse": 16, "text": "And Jonathan Saul's son arose, and went to David into the wood, and strengthened his hand in God."}],
        24: [{"verse": 12, "text": "The LORD judge between me and thee, and the LORD avenge me of thee: but mine hand shall not be upon thee."}],
        25: [{"verse": 32, "text": "Blessed be the LORD God of Israel, which sent thee this day to meet me."}],
        26: [{"verse": 24, "text": "And, behold, as thy life was much set by this day in mine eyes, so let my life be much set by in the eyes of the LORD."}],
        27: [{"verse": 1, "text": "And David said in his heart, I shall now perish one day by the hand of Saul."}],
        28: [{"verse": 15, "text": "And Samuel said to Saul, Why hast thou disquieted me, to bring me up?"}],
        29: [{"verse": 6, "text": "As the LORD liveth, thou hast been upright."}],
        30: [{"verse": 6, "text": "But David encouraged himself in the LORD his God."}],
        31: [{"verse": 4, "text": "Then said Saul unto his armourbearer, Draw thy sword, and thrust me through therewith."}]
    },
    "2 Samuel": {
        1: [{"verse": 23, "text": "Saul and Jonathan were lovely and pleasant in their lives, and in their death they were not divided."},
            {"verse": 27, "text": "How are the mighty fallen, and the weapons of war perished!"}],
        2: [{"verse": 7, "text": "Therefore now let your hands be strengthened, and be ye valiant."}],
        3: [{"verse": 38, "text": "Know ye not that there is a prince and a great man fallen this day in Israel?"}],
        4: [{"verse": 9, "text": "As the LORD liveth, who hath redeemed my soul out of all adversity."}],
        5: [{"verse": 10, "text": "And David went on, and grew great, and the LORD God of hosts was with him."}],
        6: [{"verse": 14, "text": "And David danced before the LORD with all his might."}],
        7: [{"verse": 16, "text": "And thine house and thy kingdom shall be established for ever before thee: thy throne shall be established for ever."},
            {"verse": 22, "text": "Wherefore thou art great, O LORD God: for there is none like thee, neither is there any God beside thee."}],
        8: [{"verse": 6, "text": "And the LORD preserved David whithersoever he went."}],
        9: [{"verse": 3, "text": "Is there not yet any of the house of Saul, that I may shew the kindness of God unto him?"}],
        10: [{"verse": 12, "text": "Be of good courage, and let us play the men for our people, and for the cities of our God: and the LORD do that which seemeth him good."}],
        11: [{"verse": 27, "text": "But the thing that David had done displeased the LORD."}],
        12: [{"verse": 7, "text": "And Nathan said to David, Thou art the man."},
             {"verse": 13, "text": "And David said unto Nathan, I have sinned against the LORD. And Nathan said unto David, The LORD also hath put away thy sin."}],
        13: [{"verse": 39, "text": "And the soul of king David longed to go forth unto Absalom."}],
        14: [{"verse": 14, "text": "For we must needs die, and are as water spilt on the ground, which cannot be gathered up again."}],
        15: [{"verse": 26, "text": "But if he thus say, I have no delight in thee; behold, here am I, let him do to me as seemeth good unto him."}],
        16: [{"verse": 12, "text": "It may be that the LORD will look on mine affliction, and that the LORD will requite me good for his cursing this day."}],
        17: [{"verse": 14, "text": "For the LORD had appointed to defeat the good counsel of Ahithophel."}],
        18: [{"verse": 33, "text": "O my son Absalom, my son, my son Absalom! would God I had died for thee, O Absalom, my son, my son!"}],
        19: [{"verse": 22, "text": "What have I to do with you, ye sons of Zeruiah, that ye should this day be adversaries unto me?"}],
        20: [{"verse": 19, "text": "I am one of them that are peaceable and faithful in Israel."}],
        21: [{"verse": 22, "text": "These four were born to the giant in Gath, and fell by the hand of David, and by the hand of his servants."}],
        22: [{"verse": 2, "text": "The LORD is my rock, and my fortress, and my deliverer."},
             {"verse": 3, "text": "The God of my rock; in him will I trust: he is my shield, and the horn of my salvation, my high tower, and my refuge, my saviour."},
             {"verse": 47, "text": "The LORD liveth; and blessed be my rock; and exalted be the God of the rock of my salvation."}],
        23: [{"verse": 2, "text": "The Spirit of the LORD spake by me, and his word was in my tongue."},
             {"verse": 3, "text": "The God of Israel said, the Rock of Israel spake to me, He that ruleth over men must be just, ruling in the fear of God."}],
        24: [{"verse": 14, "text": "Let us fall now into the hand of the LORD; for his mercies are great."},
             {"verse": 24, "text": "Neither will I offer burnt offerings unto the LORD my God of that which doth cost me nothing."}]
    },
    "1 Kings": {
        1: [{"verse": 30, "text": "Even as I sware unto thee by the LORD God of Israel, saying, Assuredly Solomon thy son shall reign after me."}],
        2: [{"verse": 2, "text": "I go the way of all the earth: be thou strong therefore, and shew thyself a man."},
            {"verse": 3, "text": "And keep the charge of the LORD thy God, to walk in his ways, to keep his statutes."}],
        3: [{"verse": 9, "text": "Give therefore thy servant an understanding heart to judge thy people, that I may discern between good and bad."},
            {"verse": 12, "text": "Behold, I have done according to thy words: lo, I have given thee a wise and an understanding heart."}],
        4: [{"verse": 29, "text": "And God gave Solomon wisdom and understanding exceeding much, and largeness of heart, even as the sand that is on the sea shore."}],
        5: [{"verse": 12, "text": "And the LORD gave Solomon wisdom, as he promised him."}],
        6: [{"verse": 12, "text": "Concerning this house which thou art in building, if thou wilt walk in my statutes, and execute my judgments."},
            {"verse": 13, "text": "And I will dwell among the children of Israel, and will not forsake my people Israel."}],
        7: [{"verse": 51, "text": "So was ended all the work that king Solomon made for the house of the LORD."}],
        8: [{"verse": 27, "text": "But will God indeed dwell on the earth? behold, the heaven and heaven of heavens cannot contain thee."},
            {"verse": 56, "text": "Blessed be the LORD, that hath given rest unto his people Israel, according to all that he promised."},
            {"verse": 60, "text": "That all the people of the earth may know that the LORD is God, and that there is none else."}],
        9: [{"verse": 3, "text": "I have heard thy prayer and thy supplication, that thou hast made before me: I have hallowed this house."},
            {"verse": 4, "text": "And if thou wilt walk before me, as David thy father walked, in integrity of heart, and in uprightness."}],
        10: [{"verse": 9, "text": "Blessed be the LORD thy God, which delighted in thee, to set thee on the throne of Israel."}],
        11: [{"verse": 4, "text": "For it came to pass, when Solomon was old, that his wives turned away his heart after other gods."},
             {"verse": 11, "text": "Forasmuch as this is done of thee, and thou hast not kept my covenant and my statutes."}],
        12: [{"verse": 24, "text": "Thus saith the LORD, Ye shall not go up, nor fight against your brethren the children of Israel."}],
        13: [{"verse": 2, "text": "O altar, altar, thus saith the LORD; Behold, a child shall be born unto the house of David, Josiah by name."}],
        14: [{"verse": 13, "text": "In him there is found some good thing toward the LORD God of Israel."}],
        15: [{"verse": 5, "text": "Because David did that which was right in the eyes of the LORD, and turned not aside from any thing that he commanded him."}],
        16: [{"verse": 30, "text": "And Ahab the son of Omri did evil in the sight of the LORD above all that were before him."}],
        17: [{"verse": 14, "text": "The barrel of meal shall not waste, neither shall the cruse of oil fail."},
             {"verse": 24, "text": "And the woman said to Elijah, Now by this I know that thou art a man of God."}],
        18: [{"verse": 21, "text": "How long halt ye between two opinions? if the LORD be God, follow him: but if Baal, then follow him."},
             {"verse": 38, "text": "Then the fire of the LORD fell, and consumed the burnt sacrifice, and the wood, and the stones, and the dust."},
             {"verse": 39, "text": "And when all the people saw it, they fell on their faces: and they said, The LORD, he is the God; the LORD, he is the God."}],
        19: [{"verse": 11, "text": "And, behold, the LORD passed by, and a great and strong wind rent the mountains."},
             {"verse": 12, "text": "And after the earthquake a fire; but the LORD was not in the fire: and after the fire a still small voice."},
             {"verse": 18, "text": "Yet I have left me seven thousand in Israel, all the knees which have not bowed unto Baal."}],
        20: [{"verse": 28, "text": "Thus saith the LORD, Because the Syrians have said, The LORD is God of the hills, but he is not God of the valleys, therefore will I deliver all this great multitude into thine hand."}],
        21: [{"verse": 29, "text": "Seest thou how Ahab humbleth himself before me? because he humbleth himself before me, I will not bring the evil in his days."}],
        22: [{"verse": 14, "text": "What the LORD saith unto me, that will I speak."}]
    },
    "2 Kings": {
        1: [{"verse": 3, "text": "Is it not because there is not a God in Israel, that ye go to enquire of Baalzebub the god of Ekron?"}],
        2: [{"verse": 9, "text": "And Elisha said, I pray thee, let a double portion of thy spirit be upon me."},
            {"verse": 11, "text": "And it came to pass, as they still went on, and talked, that, behold, there appeared a chariot of fire, and horses of fire."}],
        3: [{"verse": 18, "text": "And this is but a light thing in the sight of the LORD: he will deliver the Moabites also into your hand."}],
        4: [{"verse": 2, "text": "And Elisha said unto her, What shall I do for thee? tell me, what hast thou in the house?"},
            {"verse": 44, "text": "They shall eat, and shall leave thereof, according to the word of the LORD."}],
        5: [{"verse": 14, "text": "Then went he down, and dipped himself seven times in Jordan, according to the saying of the man of God: and his flesh came again like unto the flesh of a little child, and he was clean."},
            {"verse": 15, "text": "Now I know that there is no God in all the earth, but in Israel."}],
        6: [{"verse": 16, "text": "Fear not: for they that be with us are more than they that be with them."},
            {"verse": 17, "text": "And Elisha prayed, and said, LORD, I pray thee, open his eyes, that he may see. And the LORD opened the eyes of the young man; and he saw: and, behold, the mountain was full of horses and chariots of fire round about Elisha."}],
        7: [{"verse": 9, "text": "We do not well: this day is a day of good tidings, and we hold our peace."}],
        8: [{"verse": 19, "text": "Yet the LORD would not destroy Judah for David his servant's sake, as he promised him to give him alway a light."}],
        9: [{"verse": 6, "text": "Thus saith the LORD God of Israel, I have anointed thee king over the people of the LORD, even over Israel."}],
        10: [{"verse": 30, "text": "Because thou hast done well in executing that which is right in mine eyes."}],
        11: [{"verse": 17, "text": "And Jehoiada made a covenant between the LORD and the king and the people, that they should be the LORD's people."}],
        12: [{"verse": 2, "text": "And Jehoash did that which was right in the sight of the LORD all his days."}],
        13: [{"verse": 4, "text": "And Jehoahaz besought the LORD, and the LORD hearkened unto him."}],
        14: [{"verse": 27, "text": "And the LORD said not that he would blot out the name of Israel from under heaven."}],
        15: [{"verse": 5, "text": "And the LORD smote the king, so that he was a leper unto the day of his death."}],
        16: [{"verse": 2, "text": "Twenty years old was Ahaz when he began to reign."}],
        17: [{"verse": 13, "text": "Yet the LORD testified against Israel, and against Judah, by all the prophets."},
             {"verse": 15, "text": "And they rejected his statutes, and his covenant that he made with their fathers."}],
        18: [{"verse": 5, "text": "He trusted in the LORD God of Israel; so that after him was none like him among all the kings of Judah."},
             {"verse": 6, "text": "For he clave to the LORD, and departed not from following him, but kept his commandments."}],
        19: [{"verse": 19, "text": "Now therefore, O LORD our God, I beseech thee, save thou us out of his hand, that all the kingdoms of the earth may know that thou art the LORD God, even thou only."},
             {"verse": 35, "text": "And it came to pass that night, that the angel of the LORD went out, and smote in the camp of the Assyrians an hundred fourscore and five thousand."}],
        20: [{"verse": 5, "text": "I have heard thy prayer, I have seen thy tears: behold, I will heal thee."}],
        21: [{"verse": 2, "text": "And he did that which was evil in the sight of the LORD."}],
        22: [{"verse": 2, "text": "And he did that which was right in the sight of the LORD, and walked in all the way of David his father."},
             {"verse": 8, "text": "I have found the book of the law in the house of the LORD."}],
        23: [{"verse": 25, "text": "And like unto him was there no king before him, that turned to the LORD with all his heart, and with all his soul, and with all his might."}],
        24: [{"verse": 3, "text": "Surely at the commandment of the LORD came this upon Judah, to remove them out of his sight."}],
        25: [{"verse": 27, "text": "And it came to pass in the seven and thirtieth year of the captivity of Jehoiachin king of Judah."}]
    },
    "1 Chronicles": {
        1: [{"verse": 1, "text": "Adam, Sheth, Enosh."}],
        2: [{"verse": 3, "text": "The sons of Judah; Er, and Onan, and Shelah."}],
        3: [{"verse": 1, "text": "Now these were the sons of David, which were born unto him in Hebron."}],
        4: [{"verse": 10, "text": "And Jabez called on the God of Israel, saying, Oh that thou wouldest bless me indeed, and enlarge my coast, and that thine hand might be with me, and that thou wouldest keep me from evil, that it may not grieve me! And God granted him that which he requested."}],
        5: [{"verse": 20, "text": "And they were helped against them, and the Hagarites were delivered into their hand, and all that were with them: for they cried to God in the battle, and he was intreated of them; because they put their trust in him."}],
        6: [{"verse": 49, "text": "But Aaron and his sons offered upon the altar of the burnt offering, and on the altar of incense."}],
        7: [{"verse": 22, "text": "And Ephraim their father mourned many days, and his brethren came to comfort him."}],
        8: [{"verse": 40, "text": "And the sons of Ulam were mighty men of valour, archers."}],
        9: [{"verse": 13, "text": "And their brethren, heads of the house of their fathers, a thousand and seven hundred and threescore; very able men for the work of the service of the house of God."}],
        10: [{"verse": 13, "text": "So Saul died for his transgression which he committed against the LORD, even against the word of the LORD, which he kept not."},
             {"verse": 14, "text": "And enquired not of the LORD: therefore he slew him, and turned the kingdom unto David the son of Jesse."}],
        11: [{"verse": 9, "text": "So David waxed greater and greater: for the LORD of hosts was with him."}],
        12: [{"verse": 18, "text": "Then the spirit came upon Amasai, who was chief of the captains, and he said, Thine are we, David, and on thy side, thou son of Jesse: peace, peace be unto thee."}],
        13: [{"verse": 8, "text": "And David and all Israel played before God with all their might, and with singing, and with harps, and with psalteries."}],
        14: [{"verse": 2, "text": "And David perceived that the LORD had confirmed him king over Israel, for his kingdom was lifted up on high."}],
        15: [{"verse": 28, "text": "Thus all Israel brought up the ark of the covenant of the LORD with shouting, and with sound of the cornet, and with trumpets."}],
        16: [{"verse": 8, "text": "Give thanks unto the LORD, call upon his name, make known his deeds among the people."},
             {"verse": 11, "text": "Seek the LORD and his strength, seek his face continually."},
             {"verse": 34, "text": "O give thanks unto the LORD; for he is good; for his mercy endureth for ever."}],
        17: [{"verse": 14, "text": "But I will settle him in mine house and in my kingdom for ever: and his throne shall be established for evermore."}],
        18: [{"verse": 14, "text": "So David reigned over all Israel, and executed judgment and justice among all his people."}],
        19: [{"verse": 13, "text": "Be of good courage, and let us behave ourselves valiantly for our people, and for the cities of our God."}],
        20: [{"verse": 1, "text": "And it came to pass, that after the year was expired, at the time that kings go out to battle."}],
        21: [{"verse": 13, "text": "Let me fall now into the hand of the LORD; for very great are his mercies."}],
        22: [{"verse": 13, "text": "Then shalt thou prosper, if thou takest heed to fulfil the statutes and judgments which the LORD charged Moses with concerning Israel: be strong, and of good courage; dread not, nor be dismayed."},
             {"verse": 19, "text": "Now set your heart and your soul to seek the LORD your God."}],
        23: [{"verse": 30, "text": "And to stand every morning to thank and praise the LORD, and likewise at even."}],
        24: [{"verse": 19, "text": "These were the orderings of them in their service to come into the house of the LORD."}],
        25: [{"verse": 1, "text": "Moreover David and the captains of the host separated to the service of the sons of Asaph, and of Heman, and of Jeduthun, who should prophesy with harps."}],
        26: [{"verse": 30, "text": "And of the Hebronites, Hashabiah and his brethren, men of valour, a thousand and seven hundred, were officers among them of Israel on this side Jordan westward in all the business of the LORD."}],
        27: [{"verse": 23, "text": "But David took not the number of them from twenty years old and under: because the LORD had said he would increase Israel like to the stars of the heavens."}],
        28: [{"verse": 9, "text": "And thou, Solomon my son, know thou the God of thy father, and serve him with a perfect heart and with a willing mind: for the LORD searcheth all hearts."},
             {"verse": 20, "text": "And David said to Solomon his son, Be strong and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee."}],
        29: [{"verse": 11, "text": "Thine, O LORD, is the greatness, and the power, and the glory, and the victory, and the majesty: for all that is in the heaven and in the earth is thine."},
             {"verse": 14, "text": "But who am I, and what is my people, that we should be able to offer so willingly after this sort? for all things come of thee, and of thine own have we given thee."}]
    },
    "2 Chronicles": {
        1: [{"verse": 10, "text": "Give me now wisdom and knowledge, that I may go out and come in before this people."},
            {"verse": 12, "text": "Wisdom and knowledge is granted unto thee; and I will give thee riches, and wealth, and honour."}],
        2: [{"verse": 6, "text": "But who is able to build him an house, seeing the heaven and heaven of heavens cannot contain him?"}],
        3: [{"verse": 1, "text": "Then Solomon began to build the house of the LORD at Jerusalem in mount Moriah."}],
        4: [{"verse": 19, "text": "And Solomon made all the vessels that were for the house of God."}],
        5: [{"verse": 13, "text": "For he is good; for his mercy endureth for ever."},
            {"verse": 14, "text": "The house was filled with a cloud, even the house of the LORD; So that the priests could not stand to minister by reason of the cloud: for the glory of the LORD had filled the house of God."}],
        6: [{"verse": 14, "text": "There is no God like thee in the heaven, nor in the earth; which keepest covenant, and shewest mercy unto thy servants."},
            {"verse": 18, "text": "But will God in very deed dwell with men on the earth? behold, heaven and the heaven of heavens cannot contain thee."}],
        7: [{"verse": 1, "text": "Now when Solomon had made an end of praying, the fire came down from heaven, and consumed the burnt offering and the sacrifices; and the glory of the LORD filled the house."},
            {"verse": 14, "text": "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land."}],
        8: [{"verse": 11, "text": "And Solomon brought up the daughter of Pharaoh out of the city of David."}],
        9: [{"verse": 8, "text": "Blessed be the LORD thy God, which delighted in thee to set thee on his throne."}],
        10: [{"verse": 19, "text": "And Israel rebelled against the house of David unto this day."}],
        11: [{"verse": 4, "text": "Thus saith the LORD, Ye shall not go up, nor fight against your brethren: return every man to his house."}],
        12: [{"verse": 6, "text": "Whereupon the princes of Israel and the king humbled themselves; and they said, The LORD is righteous."},
             {"verse": 7, "text": "They have humbled themselves; therefore I will not destroy them, but I will grant them some deliverance."}],
        13: [{"verse": 18, "text": "Thus the children of Israel were brought under at that time, and the children of Judah prevailed, because they relied upon the LORD God of their fathers."}],
        14: [{"verse": 11, "text": "And Asa cried unto the LORD his God, and said, LORD, it is nothing with thee to help, whether with many, or with them that have no power: help us, O LORD our God; for we rest on thee."}],
        15: [{"verse": 2, "text": "The LORD is with you, while ye be with him; and if ye seek him, he will be found of you; but if ye forsake him, he will forsake you."},
             {"verse": 7, "text": "Be ye strong therefore, and let not your hands be weak: for your work shall be rewarded."}],
        16: [{"verse": 9, "text": "For the eyes of the LORD run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him."}],
        17: [{"verse": 6, "text": "And his heart was lifted up in the ways of the LORD."}],
        18: [{"verse": 13, "text": "As the LORD liveth, even what my God saith, that will I speak."}],
        19: [{"verse": 6, "text": "Take heed what ye do: for ye judge not for man, but for the LORD, who is with you in the judgment."},
             {"verse": 7, "text": "Wherefore now let the fear of the LORD be upon you; take heed and do it: for there is no iniquity with the LORD our God, nor respect of persons, nor taking of gifts."}],
        20: [{"verse": 12, "text": "O our God, wilt thou not judge them? for we have no might against this great company that cometh against us; neither know we what to do: but our eyes are upon thee."},
             {"verse": 15, "text": "Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God's."},
             {"verse": 17, "text": "Ye shall not need to fight in this battle: set yourselves, stand ye still, and see the salvation of the LORD with you."}],
        21: [{"verse": 7, "text": "Howbeit the LORD would not destroy the house of David, because of the covenant that he had made with David."}],
        22: [{"verse": 4, "text": "Wherefore he did evil in the sight of the LORD like the house of Ahab."}],
        23: [{"verse": 16, "text": "And Jehoiada made a covenant between him, and between all the people, and between the king, that they should be the LORD's people."}],
        24: [{"verse": 20, "text": "And the Spirit of God came upon Zechariah the son of Jehoiada the priest."}],
        25: [{"verse": 9, "text": "The LORD is able to give thee much more than this."}],
        26: [{"verse": 5, "text": "And he sought God in the days of Zechariah, who had understanding in the visions of God: and as long as he sought the LORD, God made him to prosper."},
             {"verse": 16, "text": "But when he was strong, his heart was lifted up to his destruction: for he transgressed against the LORD his God."}],
        27: [{"verse": 6, "text": "So Jotham became mighty, because he prepared his ways before the LORD his God."}],
        28: [{"verse": 9, "text": "Behold, because the LORD God of your fathers was wroth with Judah, he hath delivered them into your hand."}],
        29: [{"verse": 11, "text": "My sons, be not now negligent: for the LORD hath chosen you to stand before him, to serve him."}],
        30: [{"verse": 9, "text": "For if ye turn again unto the LORD, your brethren and your children shall find compassion before them that lead them captive."}],
        31: [{"verse": 21, "text": "And in every work that he began in the service of the house of God, and in the law, and in the commandments, to seek his God, he did it with all his heart, and prospered."}],
        32: [{"verse": 7, "text": "Be strong and courageous, be not afraid nor dismayed for the king of Assyria, nor for all the multitude that is with him: for there be more with us than with him."},
             {"verse": 8, "text": "With him is an arm of flesh; but with us is the LORD our God to help us, and to fight our battles."}],
        33: [{"verse": 12, "text": "And when he was in affliction, he besought the LORD his God, and humbled himself greatly before the God of his fathers."},
             {"verse": 13, "text": "And prayed unto him: and he was intreated of him, and heard his supplication."}],
        34: [{"verse": 27, "text": "Because thine heart was tender, and thou didst humble thyself before God."}],
        35: [{"verse": 3, "text": "Put the holy ark in the house which Solomon the son of David king of Israel did build."}],
        36: [{"verse": 15, "text": "And the LORD God of their fathers sent to them by his messengers, rising up betimes, and sending; because he had compassion on his people."},
             {"verse": 16, "text": "But they mocked the messengers of God, and despised his words, and misused his prophets."},
             {"verse": 23, "text": "Thus saith Cyrus king of Persia, All the kingdoms of the earth hath the LORD God of heaven given me; and he hath charged me to build him an house in Jerusalem."}]
    },
    "Ezra": {
        1: [{"verse": 3, "text": "Who is there among you of all his people? his God be with him, and let him go up to Jerusalem."}],
        2: [{"verse": 68, "text": "And some of the chief of the fathers, when they came to the house of the LORD which is at Jerusalem, offered freely for the house of God to set it up in his place."}],
        3: [{"verse": 11, "text": "And they sang together by course in praising and giving thanks unto the LORD; because he is good, for his mercy endureth for ever toward Israel."}],
        4: [{"verse": 3, "text": "But Zerubbabel, and Jeshua, and the rest of the chief of the fathers of Israel, said unto them, Ye have nothing to do with us to build an house unto our God."}],
        5: [{"verse": 8, "text": "This work goeth fast on, and prospereth in their hands."}],
        6: [{"verse": 14, "text": "And they builded, and finished it, according to the commandment of the God of Israel."},
            {"verse": 22, "text": "And kept the feast of unleavened bread seven days with joy: for the LORD had made them joyful."}],
        7: [{"verse": 6, "text": "This Ezra went up from Babylon; and he was a ready scribe in the law of Moses, which the LORD God of Israel had given."},
            {"verse": 9, "text": "For upon the first day of the first month began he to go up from Babylon, and on the first day of the fifth month came he to Jerusalem, according to the good hand of his God upon him."},
            {"verse": 10, "text": "For Ezra had prepared his heart to seek the law of the LORD, and to do it, and to teach in Israel statutes and judgments."}],
        8: [{"verse": 22, "text": "The hand of our God is upon all them for good that seek him; but his power and his wrath is against all them that forsake him."},
            {"verse": 23, "text": "So we fasted and besought our God for this: and he was intreated of us."}],
        9: [{"verse": 6, "text": "O my God, I am ashamed and blush to lift up my face to thee, my God: for our iniquities are increased over our head."}],
        10: [{"verse": 11, "text": "Now therefore make confession unto the LORD God of your fathers, and do his pleasure."}]
    },
    "Nehemiah": {
        1: [{"verse": 5, "text": "I beseech thee, O LORD God of heaven, the great and terrible God, that keepeth covenant and mercy for them that love him and observe his commandments."},
            {"verse": 11, "text": "O Lord, I beseech thee, let now thine ear be attentive to the prayer of thy servant."}],
        2: [{"verse": 8, "text": "And the king granted me, according to the good hand of my God upon me."},
            {"verse": 18, "text": "Then I told them of the hand of my God which was good upon me; as also the king's words that he had spoken unto me. And they said, Let us rise up and build. So they strengthened their hands for this good work."},
            {"verse": 20, "text": "The God of heaven, he will prosper us; therefore we his servants will arise and build."}],
        3: [{"verse": 1, "text": "Then Eliashib the high priest rose up with his brethren the priests, and they builded the sheep gate."}],
        4: [{"verse": 9, "text": "Nevertheless we made our prayer unto our God, and set a watch against them day and night."},
            {"verse": 14, "text": "Be not ye afraid of them: remember the Lord, which is great and terrible, and fight for your brethren."},
            {"verse": 20, "text": "Our God shall fight for us."}],
        5: [{"verse": 19, "text": "Think upon me, my God, for good, according to all that I have done for this people."}],
        6: [{"verse": 9, "text": "For they all made us afraid, saying, Their hands shall be weakened from the work, that it be not done. Now therefore, O God, strengthen my hands."},
            {"verse": 15, "text": "So the wall was finished in the twenty and fifth day of the month Elul, in fifty and two days."},
            {"verse": 16, "text": "And it came to pass, that when all our enemies heard thereof, and all the heathen that were about us saw these things, they were much cast down in their own eyes: for they perceived that this work was wrought of our God."}],
        7: [{"verse": 5, "text": "And my God put into mine heart to gather together the nobles, and the rulers, and the people."}],
        8: [{"verse": 10, "text": "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength."}],
        9: [{"verse": 5, "text": "Stand up and bless the LORD your God for ever and ever."},
            {"verse": 6, "text": "Thou, even thou, art LORD alone; thou hast made heaven, the heaven of heavens, with all their host, the earth, and all things that are therein."},
            {"verse": 17, "text": "But thou art a God ready to pardon, gracious and merciful, slow to anger, and of great kindness."}],
        10: [{"verse": 29, "text": "They clave to their brethren, their nobles, and entered into a curse, and into an oath, to walk in God's law."}],
        11: [{"verse": 2, "text": "And the people blessed all the men, that willingly offered themselves to dwell at Jerusalem."}],
        12: [{"verse": 43, "text": "Also that day they offered great sacrifices, and rejoiced: for God had made them rejoice with great joy."}],
        13: [{"verse": 22, "text": "Remember me, O my God, concerning this, and spare me according to the greatness of thy mercy."},
             {"verse": 31, "text": "Remember me, O my God, for good."}]
    },
    "Job": {
        1: [{"verse": 1, "text": "There was a man in the land of Uz, whose name was Job; and that man was perfect and upright, and one that feared God, and eschewed evil."},
            {"verse": 21, "text": "Naked came I out of my mother's womb, and naked shall I return thither: the LORD gave, and the LORD hath taken away; blessed be the name of the LORD."},
            {"verse": 22, "text": "In all this Job sinned not, nor charged God foolishly."}],
        2: [{"verse": 10, "text": "Shall we receive good at the hand of God, and shall we not receive evil? In all this did not Job sin with his lips."}],
        3: [{"verse": 17, "text": "There the wicked cease from troubling; and there the weary be at rest."}],
        4: [{"verse": 17, "text": "Shall mortal man be more just than God? shall a man be more pure than his maker?"}],
        5: [{"verse": 17, "text": "Behold, happy is the man whom God correcteth: therefore despise not thou the chastening of the Almighty."},
            {"verse": 18, "text": "For he maketh sore, and bindeth up: he woundeth, and his hands make whole."}],
        6: [{"verse": 14, "text": "To him that is afflicted pity should be shewed from his friend."}],
        7: [{"verse": 17, "text": "What is man, that thou shouldest magnify him? and that thou shouldest set thine heart upon him?"}],
        8: [{"verse": 5, "text": "If thou wouldest seek unto God betimes, and make thy supplication to the Almighty."},
            {"verse": 6, "text": "If thou wert pure and upright; surely now he would awake for thee, and make the habitation of thy righteousness prosperous."}],
        9: [{"verse": 10, "text": "Which doeth great things past finding out; yea, and wonders without number."}],
        10: [{"verse": 12, "text": "Thou hast granted me life and favour, and thy visitation hath preserved my spirit."}],
        11: [{"verse": 7, "text": "Canst thou by searching find out God? canst thou find out the Almighty unto perfection?"}],
        12: [{"verse": 7, "text": "But ask now the beasts, and they shall teach thee; and the fowls of the air, and they shall tell thee."},
             {"verse": 9, "text": "Who knoweth not in all these that the hand of the LORD hath wrought this?"},
             {"verse": 13, "text": "With him is wisdom and strength, he hath counsel and understanding."}],
        13: [{"verse": 15, "text": "Though he slay me, yet will I trust in him: but I will maintain mine own ways before him."}],
        14: [{"verse": 14, "text": "If a man die, shall he live again? all the days of my appointed time will I wait, till my change come."}],
        15: [{"verse": 15, "text": "Behold, he putteth no trust in his saints; yea, the heavens are not clean in his sight."}],
        16: [{"verse": 19, "text": "Also now, behold, my witness is in heaven, and my record is on high."}],
        17: [{"verse": 9, "text": "The righteous also shall hold on his way, and he that hath clean hands shall be stronger and stronger."}],
        18: [{"verse": 21, "text": "Surely such are the dwellings of the wicked, and this is the place of him that knoweth not God."}],
        19: [{"verse": 25, "text": "For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth."},
             {"verse": 26, "text": "And though after my skin worms destroy this body, yet in my flesh shall I see God."}],
        20: [{"verse": 29, "text": "This is the portion of a wicked man from God, and the heritage appointed unto him by God."}],
        21: [{"verse": 22, "text": "Shall any teach God knowledge? seeing he judgeth those that are high."}],
        22: [{"verse": 21, "text": "Acquaint now thyself with him, and be at peace: thereby good shall come unto thee."}],
        23: [{"verse": 10, "text": "But he knoweth the way that I take: when he hath tried me, I shall come forth as gold."}],
        24: [{"verse": 1, "text": "Why, seeing times are not hidden from the Almighty, do they that know him not see his days?"}],
        25: [{"verse": 4, "text": "How then can man be justified with God? or how can he be clean that is born of a woman?"}],
        26: [{"verse": 14, "text": "Lo, these are parts of his ways: but how little a portion is heard of him? but the thunder of his power who can understand?"}],
        27: [{"verse": 3, "text": "All the while my breath is in me, and the spirit of God is in my nostrils."},
             {"verse": 5, "text": "God forbid that I should justify you: till I die I will not remove mine integrity from me."}],
        28: [{"verse": 12, "text": "But where shall wisdom be found? and where is the place of understanding?"},
             {"verse": 28, "text": "And unto man he said, Behold, the fear of the Lord, that is wisdom; and to depart from evil is understanding."}],
        29: [{"verse": 4, "text": "As I was in the days of my youth, when the secret of God was upon my tabernacle."}],
        30: [{"verse": 20, "text": "I cry unto thee, and thou dost not hear me: I stand up, and thou regardest me not."}],
        31: [{"verse": 4, "text": "Doth not he see my ways, and count all my steps?"}],
        32: [{"verse": 8, "text": "But there is a spirit in man: and the inspiration of the Almighty giveth them understanding."}],
        33: [{"verse": 4, "text": "The Spirit of God hath made me, and the breath of the Almighty hath given me life."}],
        34: [{"verse": 10, "text": "Far be it from God, that he should do wickedness; and from the Almighty, that he should commit iniquity."},
             {"verse": 12, "text": "Yea, surely God will not do wickedly, neither will the Almighty pervert judgment."}],
        35: [{"verse": 10, "text": "But none saith, Where is God my maker, who giveth songs in the night."}],
        36: [{"verse": 5, "text": "Behold, God is mighty, and despiseth not any: he is mighty in strength and wisdom."},
             {"verse": 22, "text": "Behold, God exalteth by his power: who teacheth like him?"},
             {"verse": 26, "text": "Behold, God is great, and we know him not, neither can the number of his years be searched out."}],
        37: [{"verse": 5, "text": "God thundereth marvellously with his voice; great things doeth he, which we cannot comprehend."},
             {"verse": 23, "text": "Touching the Almighty, we cannot find him out: he is excellent in power, and in judgment."}],
        38: [{"verse": 1, "text": "Then the LORD answered Job out of the whirlwind."},
             {"verse": 4, "text": "Where wast thou when I laid the foundations of the earth? declare, if thou hast understanding."},
             {"verse": 7, "text": "When the morning stars sang together, and all the sons of God shouted for joy?"}],
        39: [{"verse": 1, "text": "Knowest thou the time when the wild goats of the rock bring forth?"}],
        40: [{"verse": 2, "text": "Shall he that contendeth with the Almighty instruct him? he that reproveth God, let him answer it."},
             {"verse": 4, "text": "Behold, I am vile; what shall I answer thee? I will lay mine hand upon my mouth."}],
        41: [{"verse": 11, "text": "Who hath prevented me, that I should repay him? whatsoever is under the whole heaven is mine."}],
        42: [{"verse": 2, "text": "I know that thou canst do every thing, and that no thought can be withholden from thee."},
             {"verse": 5, "text": "I have heard of thee by the hearing of the ear: but now mine eye seeth thee."},
             {"verse": 6, "text": "Wherefore I abhor myself, and repent in dust and ashes."},
             {"verse": 10, "text": "And the LORD turned the captivity of Job, when he prayed for his friends: also the LORD gave Job twice as much as he had before."},
             {"verse": 12, "text": "So the LORD blessed the latter end of Job more than his beginning."}]
    },
    "Proverbs": {
        1: [{"verse": 7, "text": "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction."}],
        2: [{"verse": 6, "text": "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding."}],
        3: [{"verse": 5, "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding."},
            {"verse": 6, "text": "In all thy ways acknowledge him, and he shall direct thy paths."}],
        4: [{"verse": 7, "text": "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding."},
            {"verse": 23, "text": "Keep thy heart with all diligence; for out of it are the issues of life."}],
        5: [{"verse": 21, "text": "For the ways of man are before the eyes of the LORD, and he pondereth all his goings."}],
        6: [{"verse": 16, "text": "These six things doth the LORD hate: yea, seven are an abomination unto him."}],
        7: [{"verse": 1, "text": "My son, keep my words, and lay up my commandments with thee."}],
        8: [{"verse": 11, "text": "For wisdom is better than rubies; and all the things that may be desired are not to be compared to it."},
            {"verse": 17, "text": "I love them that love me; and those that seek me early shall find me."}],
        9: [{"verse": 10, "text": "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding."}],
        10: [{"verse": 22, "text": "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it."}],
        11: [{"verse": 2, "text": "When pride cometh, then cometh shame: but with the lowly is wisdom."},
             {"verse": 30, "text": "The fruit of the righteous is a tree of life; and he that winneth souls is wise."}],
        12: [{"verse": 22, "text": "Lying lips are abomination to the LORD: but they that deal truly are his delight."}],
        13: [{"verse": 20, "text": "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed."},
             {"verse": 24, "text": "He that spareth his rod hateth his son: but he that loveth him chasteneth him betimes."}],
        14: [{"verse": 12, "text": "There is a way which seemeth right unto a man, but the end thereof are the ways of death."},
             {"verse": 27, "text": "The fear of the LORD is a fountain of life, to depart from the snares of death."}],
        15: [{"verse": 1, "text": "A soft answer turneth away wrath: but grievous words stir up anger."},
             {"verse": 3, "text": "The eyes of the LORD are in every place, beholding the evil and the good."}],
        16: [{"verse": 3, "text": "Commit thy works unto the LORD, and thy thoughts shall be established."},
             {"verse": 9, "text": "A man's heart deviseth his way: but the LORD directeth his steps."},
             {"verse": 18, "text": "Pride goeth before destruction, and an haughty spirit before a fall."}],
        17: [{"verse": 17, "text": "A friend loveth at all times, and a brother is born for adversity."},
             {"verse": 22, "text": "A merry heart doeth good like a medicine: but a broken spirit drieth the bones."}],
        18: [{"verse": 10, "text": "The name of the LORD is a strong tower: the righteous runneth into it, and is safe."},
             {"verse": 24, "text": "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother."}],
        19: [{"verse": 21, "text": "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand."}],
        20: [{"verse": 27, "text": "The spirit of man is the candle of the LORD, searching all the inward parts of the belly."}],
        21: [{"verse": 2, "text": "Every way of a man is right in his own eyes: but the LORD pondereth the hearts."},
             {"verse": 31, "text": "The horse is prepared against the day of battle: but safety is of the LORD."}],
        22: [{"verse": 1, "text": "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold."},
             {"verse": 6, "text": "Train up a child in the way he should go: and when he is old, he will not depart from it."}],
        23: [{"verse": 26, "text": "My son, give me thine heart, and let thine eyes observe my ways."}],
        24: [{"verse": 16, "text": "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief."}],
        25: [{"verse": 21, "text": "If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink."}],
        26: [{"verse": 11, "text": "As a dog returneth to his vomit, so a fool returneth to his folly."}],
        27: [{"verse": 1, "text": "Boast not thyself of to morrow; for thou knowest not what a day may bring forth."},
             {"verse": 17, "text": "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend."}],
        28: [{"verse": 13, "text": "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy."}],
        29: [{"verse": 18, "text": "Where there is no vision, the people perish: but he that keepeth the law, happy is he."}],
        30: [{"verse": 5, "text": "Every word of God is pure: he is a shield unto them that put their trust in him."}],
        31: [{"verse": 10, "text": "Who can find a virtuous woman? for her price is far above rubies."},
             {"verse": 30, "text": "Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised."}]
    },
    "Ecclesiastes": {
        1: [{"verse": 2, "text": "Vanity of vanities, saith the Preacher, vanity of vanities; all is vanity."},
            {"verse": 9, "text": "The thing that hath been, it is that which shall be; and that which is done is that which shall be done."}],
        2: [{"verse": 24, "text": "There is nothing better for a man, than that he should eat and drink, and that he should make his soul enjoy good in his labour. This also I saw, that it was from the hand of God."}],
        3: [{"verse": 1, "text": "To every thing there is a season, and a time to every purpose under the heaven."},
            {"verse": 11, "text": "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end."}],
        4: [{"verse": 9, "text": "Two are better than one; because they have a good reward for their labour."},
            {"verse": 12, "text": "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken."}],
        5: [{"verse": 2, "text": "Be not rash with thy mouth, and let not thine heart be hasty to utter any thing before God."},
            {"verse": 10, "text": "He that loveth silver shall not be satisfied with silver; nor he that loveth abundance with increase."}],
        6: [{"verse": 3, "text": "If a man beget an hundred children, and live many years, so that the days of his years be many, and his soul be not filled with good."}],
        7: [{"verse": 1, "text": "A good name is better than precious ointment; and the day of death than the day of one's birth."},
            {"verse": 14, "text": "In the day of prosperity be joyful, but in the day of adversity consider."}],
        8: [{"verse": 12, "text": "Though a sinner do evil an hundred times, and his days be prolonged, yet surely I know that it shall be well with them that fear God."}],
        9: [{"verse": 10, "text": "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest."},
            {"verse": 11, "text": "The race is not to the swift, nor the battle to the strong, neither yet bread to the wise."}],
        10: [{"verse": 10, "text": "If the iron be blunt, and he do not whet the edge, then must he put to more strength: but wisdom is profitable to direct."}],
        11: [{"verse": 1, "text": "Cast thy bread upon the waters: for thou shalt find it after many days."},
             {"verse": 9, "text": "Rejoice, O young man, in thy youth; and let thy heart cheer thee in the days of thy youth."}],
        12: [{"verse": 1, "text": "Remember now thy Creator in the days of thy youth, while the evil days come not."},
             {"verse": 13, "text": "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man."},
             {"verse": 14, "text": "For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil."}]
    },
    "Song of Solomon": {
        1: [{"verse": 2, "text": "Let him kiss me with the kisses of his mouth: for thy love is better than wine."},
            {"verse": 4, "text": "Draw me, we will run after thee: the king hath brought me into his chambers."}],
        2: [{"verse": 1, "text": "I am the rose of Sharon, and the lily of the valleys."},
            {"verse": 4, "text": "He brought me to the banqueting house, and his banner over me was love."},
            {"verse": 10, "text": "My beloved spake, and said unto me, Rise up, my love, my fair one, and come away."},
            {"verse": 16, "text": "My beloved is mine, and I am his."}],
        3: [{"verse": 4, "text": "It was but a little that I passed from them, but I found him whom my soul loveth: I held him, and would not let him go."}],
        4: [{"verse": 7, "text": "Thou art all fair, my love; there is no spot in thee."},
            {"verse": 9, "text": "Thou hast ravished my heart, my sister, my spouse; thou hast ravished my heart with one of thine eyes."}],
        5: [{"verse": 16, "text": "His mouth is most sweet: yea, he is altogether lovely. This is my beloved, and this is my friend."}],
        6: [{"verse": 3, "text": "I am my beloved's, and my beloved is mine: he feedeth among the lilies."}],
        7: [{"verse": 10, "text": "I am my beloved's, and his desire is toward me."}],
        8: [{"verse": 6, "text": "Set me as a seal upon thine heart, as a seal upon thine arm: for love is strong as death; jealousy is cruel as the grave."},
            {"verse": 7, "text": "Many waters cannot quench love, neither can the floods drown it."}]
    },
    "Lamentations": {
        1: [{"verse": 12, "text": "Is it nothing to you, all ye that pass by? behold, and see if there be any sorrow like unto my sorrow."}],
        2: [{"verse": 19, "text": "Arise, cry out in the night: in the beginning of the watches pour out thine heart like water before the face of the Lord."}],
        3: [{"verse": 22, "text": "It is of the LORD's mercies that we are not consumed, because his compassions fail not."},
            {"verse": 23, "text": "They are new every morning: great is thy faithfulness."},
            {"verse": 24, "text": "The LORD is my portion, saith my soul; therefore will I hope in him."},
            {"verse": 25, "text": "The LORD is good unto them that wait for him, to the soul that seeketh him."},
            {"verse": 26, "text": "It is good that a man should both hope and quietly wait for the salvation of the LORD."},
            {"verse": 40, "text": "Let us search and try our ways, and turn again to the LORD."}],
        4: [{"verse": 22, "text": "The punishment of thine iniquity is accomplished, O daughter of Zion; he will no more carry thee away into captivity."}],
        5: [{"verse": 19, "text": "Thou, O LORD, remainest for ever; thy throne from generation to generation."},
            {"verse": 21, "text": "Turn thou us unto thee, O LORD, and we shall be turned; renew our days as of old."}]
    }
}

def update_books():
    output_dir = r"C:\Users\WelCome\AndroidStudioProjects\CPASongs\app\src\main\assets\bible"

    import json

    for book_name, chapters in COMPREHENSIVE_VERSES.items():
        # Determine file name
        if book_name.startswith("1 "):
            file_name = "1_" + book_name[2:].lower().replace(" ", "_") + ".json"
        elif book_name.startswith("2 "):
            file_name = "2_" + book_name[2:].lower().replace(" ", "_") + ".json"
        else:
            file_name = book_name.lower().replace(" ", "_") + ".json"

        file_path = os.path.join(output_dir, file_name)

        if not os.path.exists(file_path):
            print(f"File not found: {file_name}")
            continue

        # Read current file
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Update chapters with comprehensive verses
        updated_chapters = []
        for chapter_data in data["chapters"]:
            ch_num = chapter_data["chapter"]
            if ch_num in chapters:
                updated_chapters.append({
                    "chapter": ch_num,
                    "verses": chapters[ch_num]
                })
            else:
                updated_chapters.append(chapter_data)

        data["chapters"] = updated_chapters

        # Write back
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False)

        print(f"Updated {book_name}")

if __name__ == "__main__":
    update_books()

