"""
Update New Testament and remaining books with meaningful key verses.
"""

import json
import os

# New Testament and remaining OT books
NEW_TESTAMENT_VERSES = {
    "Matthew": {
        1: [{"verse": 21, "text": "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins."},
            {"verse": 23, "text": "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us."}],
        2: [{"verse": 2, "text": "Where is he that is born King of the Jews? for we have seen his star in the east, and are come to worship him."},
            {"verse": 11, "text": "And when they were come into the house, they saw the young child with Mary his mother, and fell down, and worshipped him."}],
        3: [{"verse": 16, "text": "And Jesus, when he was baptized, went up straightway out of the water: and, lo, the heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him."},
            {"verse": 17, "text": "And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased."}],
        4: [{"verse": 4, "text": "Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God."},
            {"verse": 17, "text": "From that time Jesus began to preach, and to say, Repent: for the kingdom of heaven is at hand."},
            {"verse": 19, "text": "Follow me, and I will make you fishers of men."}],
        5: [{"verse": 3, "text": "Blessed are the poor in spirit: for theirs is the kingdom of heaven."},
            {"verse": 14, "text": "Ye are the light of the world. A city that is set on an hill cannot be hid."},
            {"verse": 16, "text": "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."},
            {"verse": 44, "text": "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you."},
            {"verse": 48, "text": "Be ye therefore perfect, even as your Father which is in heaven is perfect."}],
        6: [{"verse": 9, "text": "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name."},
            {"verse": 21, "text": "For where your treasure is, there will your heart be also."},
            {"verse": 33, "text": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."},
            {"verse": 34, "text": "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself."}],
        7: [{"verse": 7, "text": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you."},
            {"verse": 12, "text": "Therefore all things whatsoever ye would that men should do to you, do ye even so to them."},
            {"verse": 21, "text": "Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven; but he that doeth the will of my Father which is in heaven."}],
        8: [{"verse": 26, "text": "And he saith unto them, Why are ye fearful, O ye of little faith?"}],
        9: [{"verse": 13, "text": "But go ye and learn what that meaneth, I will have mercy, and not sacrifice: for I am not come to call the righteous, but sinners to repentance."}],
        10: [{"verse": 28, "text": "And fear not them which kill the body, but are not able to kill the soul."},
             {"verse": 39, "text": "He that findeth his life shall lose it: and he that loseth his life for my sake shall find it."}],
        11: [{"verse": 28, "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."},
             {"verse": 29, "text": "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls."},
             {"verse": 30, "text": "For my yoke is easy, and my burden is light."}],
        12: [{"verse": 36, "text": "But I say unto you, That every idle word that men shall speak, they shall give account thereof in the day of judgment."}],
        13: [{"verse": 23, "text": "But he that received seed into the good ground is he that heareth the word, and understandeth it."}],
        14: [{"verse": 27, "text": "But straightway Jesus spake unto them, saying, Be of good cheer; it is I; be not afraid."}],
        15: [{"verse": 28, "text": "Then Jesus answered and said unto her, O woman, great is thy faith: be it unto thee even as thou wilt."}],
        16: [{"verse": 15, "text": "He saith unto them, But whom say ye that I am?"},
             {"verse": 16, "text": "And Simon Peter answered and said, Thou art the Christ, the Son of the living God."},
             {"verse": 24, "text": "Then said Jesus unto his disciples, If any man will come after me, let him deny himself, and take up his cross, and follow me."},
             {"verse": 26, "text": "For what is a man profited, if he shall gain the whole world, and lose his own soul?"}],
        17: [{"verse": 5, "text": "This is my beloved Son, in whom I am well pleased; hear ye him."},
             {"verse": 20, "text": "If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you."}],
        18: [{"verse": 3, "text": "Except ye be converted, and become as little children, ye shall not enter into the kingdom of heaven."},
             {"verse": 20, "text": "For where two or three are gathered together in my name, there am I in the midst of them."}],
        19: [{"verse": 14, "text": "Suffer little children, and forbid them not, to come unto me: for of such is the kingdom of heaven."},
             {"verse": 26, "text": "With men this is impossible; but with God all things are possible."}],
        20: [{"verse": 16, "text": "So the last shall be first, and the first last."},
             {"verse": 28, "text": "Even as the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many."}],
        21: [{"verse": 22, "text": "And all things, whatsoever ye shall ask in prayer, believing, ye shall receive."}],
        22: [{"verse": 37, "text": "Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."},
             {"verse": 39, "text": "Thou shalt love thy neighbour as thyself."}],
        23: [{"verse": 11, "text": "But he that is greatest among you shall be your servant."},
             {"verse": 12, "text": "And whosoever shall exalt himself shall be abased; and he that shall humble himself shall be exalted."}],
        24: [{"verse": 35, "text": "Heaven and earth shall pass away, but my words shall not pass away."},
             {"verse": 44, "text": "Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh."}],
        25: [{"verse": 21, "text": "His lord said unto him, Well done, thou good and faithful servant."},
             {"verse": 40, "text": "Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me."}],
        26: [{"verse": 39, "text": "O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt."},
             {"verse": 41, "text": "Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak."}],
        27: [{"verse": 54, "text": "Truly this was the Son of God."}],
        28: [{"verse": 18, "text": "All power is given unto me in heaven and in earth."},
             {"verse": 19, "text": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost."},
             {"verse": 20, "text": "Lo, I am with you alway, even unto the end of the world. Amen."}]
    },
    "Mark": {
        1: [{"verse": 15, "text": "The time is fulfilled, and the kingdom of God is at hand: repent ye, and believe the gospel."},
            {"verse": 17, "text": "Come ye after me, and I will make you to become fishers of men."}],
        2: [{"verse": 17, "text": "They that are whole have no need of the physician, but they that are sick: I came not to call the righteous, but sinners to repentance."},
            {"verse": 27, "text": "The sabbath was made for man, and not man for the sabbath."}],
        3: [{"verse": 35, "text": "For whosoever shall do the will of God, the same is my brother, and my sister, and mother."}],
        4: [{"verse": 39, "text": "Peace, be still. And the wind ceased, and there was a great calm."},
            {"verse": 40, "text": "And he said unto them, Why are ye so fearful? how is it that ye have no faith?"}],
        5: [{"verse": 34, "text": "Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague."},
            {"verse": 36, "text": "Be not afraid, only believe."}],
        6: [{"verse": 34, "text": "And Jesus, when he came out, saw much people, and was moved with compassion toward them."}],
        7: [{"verse": 15, "text": "There is nothing from without a man, that entering into him can defile him: but the things which come out of him, those are they that defile the man."}],
        8: [{"verse": 34, "text": "Whosoever will come after me, let him deny himself, and take up his cross, and follow me."},
            {"verse": 36, "text": "For what shall it profit a man, if he shall gain the whole world, and lose his own soul?"}],
        9: [{"verse": 23, "text": "If thou canst believe, all things are possible to him that believeth."},
            {"verse": 35, "text": "If any man desire to be first, the same shall be last of all, and servant of all."}],
        10: [{"verse": 27, "text": "With men it is impossible, but not with God: for with God all things are possible."},
             {"verse": 45, "text": "For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many."}],
        11: [{"verse": 24, "text": "What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them."},
             {"verse": 25, "text": "And when ye stand praying, forgive, if ye have ought against any: that your Father also which is in heaven may forgive you your trespasses."}],
        12: [{"verse": 30, "text": "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment."},
             {"verse": 31, "text": "And the second is like, namely this, Thou shalt love thy neighbour as thyself."}],
        13: [{"verse": 31, "text": "Heaven and earth shall pass away: but my words shall not pass away."},
             {"verse": 33, "text": "Take ye heed, watch and pray: for ye know not when the time is."}],
        14: [{"verse": 36, "text": "And he said, Abba, Father, all things are possible unto thee; take away this cup from me: nevertheless not what I will, but what thou wilt."}],
        15: [{"verse": 39, "text": "And when the centurion, which stood over against him, saw that he so cried out, and gave up the ghost, he said, Truly this man was the Son of God."}],
        16: [{"verse": 6, "text": "Be not affrighted: Ye seek Jesus of Nazareth, which was crucified: he is risen; he is not here."},
             {"verse": 15, "text": "Go ye into all the world, and preach the gospel to every creature."}]
    },
    "Luke": {
        1: [{"verse": 37, "text": "For with God nothing shall be impossible."},
            {"verse": 46, "text": "My soul doth magnify the Lord."},
            {"verse": 47, "text": "And my spirit hath rejoiced in God my Saviour."}],
        2: [{"verse": 10, "text": "Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people."},
            {"verse": 11, "text": "For unto you is born this day in the city of David a Saviour, which is Christ the Lord."},
            {"verse": 14, "text": "Glory to God in the highest, and on earth peace, good will toward men."}],
        3: [{"verse": 22, "text": "And the Holy Ghost descended in a bodily shape like a dove upon him, and a voice came from heaven, which said, Thou art my beloved Son; in thee I am well pleased."}],
        4: [{"verse": 18, "text": "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor."},
            {"verse": 19, "text": "To preach the acceptable year of the Lord."}],
        5: [{"verse": 32, "text": "I came not to call the righteous, but sinners to repentance."}],
        6: [{"verse": 27, "text": "Love your enemies, do good to them which hate you."},
            {"verse": 31, "text": "And as ye would that men should do to you, do ye also to them likewise."},
            {"verse": 37, "text": "Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven."},
            {"verse": 38, "text": "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom."}],
        7: [{"verse": 47, "text": "Wherefore I say unto thee, Her sins, which are many, are forgiven; for she loved much."},
            {"verse": 50, "text": "Thy faith hath saved thee; go in peace."}],
        8: [{"verse": 50, "text": "Fear not: believe only, and she shall be made whole."}],
        9: [{"verse": 23, "text": "If any man will come after me, let him deny himself, and take up his cross daily, and follow me."},
            {"verse": 25, "text": "For what is a man advantaged, if he gain the whole world, and lose himself, or be cast away?"}],
        10: [{"verse": 27, "text": "Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy strength, and with all thy mind; and thy neighbour as thyself."}],
        11: [{"verse": 9, "text": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you."},
             {"verse": 13, "text": "If ye then, being evil, know how to give good gifts unto your children: how much more shall your heavenly Father give the Holy Spirit to them that ask him?"}],
        12: [{"verse": 32, "text": "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom."},
             {"verse": 34, "text": "For where your treasure is, there will your heart be also."}],
        13: [{"verse": 24, "text": "Strive to enter in at the strait gate."}],
        14: [{"verse": 11, "text": "For whosoever exalteth himself shall be abased; and he that humbleth himself shall be exalted."}],
        15: [{"verse": 7, "text": "Likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance."},
             {"verse": 10, "text": "There is joy in the presence of the angels of God over one sinner that repenteth."}],
        16: [{"verse": 10, "text": "He that is faithful in that which is least is faithful also in much."},
             {"verse": 13, "text": "No servant can serve two masters: for either he will hate the one, and love the other."}],
        17: [{"verse": 21, "text": "Neither shall they say, Lo here! or, lo there! for, behold, the kingdom of God is within you."}],
        18: [{"verse": 16, "text": "Suffer little children to come unto me, and forbid them not: for of such is the kingdom of God."},
             {"verse": 27, "text": "The things which are impossible with men are possible with God."}],
        19: [{"verse": 10, "text": "For the Son of man is come to seek and to save that which was lost."}],
        20: [{"verse": 25, "text": "Render therefore unto Caesar the things which be Caesar's, and unto God the things which be God's."}],
        21: [{"verse": 33, "text": "Heaven and earth shall pass away: but my words shall not pass away."}],
        22: [{"verse": 42, "text": "Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done."}],
        23: [{"verse": 34, "text": "Then said Jesus, Father, forgive them; for they know not what they do."},
             {"verse": 43, "text": "Verily I say unto thee, To day shalt thou be with me in paradise."},
             {"verse": 46, "text": "Father, into thy hands I commend my spirit: and having said thus, he gave up the ghost."}],
        24: [{"verse": 6, "text": "He is not here, but is risen: remember how he spake unto you when he was yet in Galilee."},
             {"verse": 32, "text": "Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?"}]
    },
    "John": {
        1: [{"verse": 1, "text": "In the beginning was the Word, and the Word was with God, and the Word was God."},
            {"verse": 12, "text": "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name."},
            {"verse": 14, "text": "And the Word was made flesh, and dwelt among us, and we beheld his glory."},
            {"verse": 29, "text": "Behold the Lamb of God, which taketh away the sin of the world."}],
        2: [{"verse": 11, "text": "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory."}],
        3: [{"verse": 3, "text": "Except a man be born again, he cannot see the kingdom of God."},
            {"verse": 16, "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."},
            {"verse": 17, "text": "For God sent not his Son into the world to condemn the world; but that the world through him might be saved."},
            {"verse": 36, "text": "He that believeth on the Son hath everlasting life."}],
        4: [{"verse": 14, "text": "But whosoever drinketh of the water that I shall give him shall never thirst."},
            {"verse": 24, "text": "God is a Spirit: and they that worship him must worship him in spirit and in truth."}],
        5: [{"verse": 24, "text": "He that heareth my word, and believeth on him that sent me, hath everlasting life."}],
        6: [{"verse": 35, "text": "I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst."},
            {"verse": 37, "text": "All that the Father giveth me shall come to me; and him that cometh to me I will in no wise cast out."},
            {"verse": 40, "text": "And this is the will of him that sent me, that every one which seeth the Son, and believeth on him, may have everlasting life."}],
        7: [{"verse": 37, "text": "If any man thirst, let him come unto me, and drink."},
            {"verse": 38, "text": "He that believeth on me, as the scripture hath said, out of his belly shall flow rivers of living water."}],
        8: [{"verse": 12, "text": "I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life."},
            {"verse": 32, "text": "And ye shall know the truth, and the truth shall make you free."},
            {"verse": 36, "text": "If the Son therefore shall make you free, ye shall be free indeed."}],
        9: [{"verse": 25, "text": "One thing I know, that, whereas I was blind, now I see."}],
        10: [{"verse": 10, "text": "I am come that they might have life, and that they might have it more abundantly."},
             {"verse": 11, "text": "I am the good shepherd: the good shepherd giveth his life for the sheep."},
             {"verse": 27, "text": "My sheep hear my voice, and I know them, and they follow me."},
             {"verse": 28, "text": "And I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand."}],
        11: [{"verse": 25, "text": "I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live."},
             {"verse": 26, "text": "And whosoever liveth and believeth in me shall never die."},
             {"verse": 35, "text": "Jesus wept."}],
        12: [{"verse": 32, "text": "And I, if I be lifted up from the earth, will draw all men unto me."}],
        13: [{"verse": 34, "text": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another."},
             {"verse": 35, "text": "By this shall all men know that ye are my disciples, if ye have love one to another."}],
        14: [{"verse": 1, "text": "Let not your heart be troubled: ye believe in God, believe also in me."},
             {"verse": 2, "text": "In my Father's house are many mansions."},
             {"verse": 6, "text": "I am the way, the truth, and the life: no man cometh unto the Father, but by me."},
             {"verse": 13, "text": "And whatsoever ye shall ask in my name, that will I do, that the Father may be glorified in the Son."},
             {"verse": 27, "text": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid."}],
        15: [{"verse": 5, "text": "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit."},
             {"verse": 7, "text": "If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you."},
             {"verse": 12, "text": "This is my commandment, That ye love one another, as I have loved you."},
             {"verse": 13, "text": "Greater love hath no man than this, that a man lay down his life for his friends."}],
        16: [{"verse": 33, "text": "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world."}],
        17: [{"verse": 3, "text": "And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent."},
             {"verse": 17, "text": "Sanctify them through thy truth: thy word is truth."}],
        18: [{"verse": 36, "text": "My kingdom is not of this world."},
             {"verse": 38, "text": "Pilate saith unto him, What is truth?"}],
        19: [{"verse": 30, "text": "It is finished: and he bowed his head, and gave up the ghost."}],
        20: [{"verse": 21, "text": "Peace be unto you: as my Father hath sent me, even so send I you."},
             {"verse": 29, "text": "Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed."},
             {"verse": 31, "text": "But these are written, that ye might believe that Jesus is the Christ, the Son of God; and that believing ye might have life through his name."}],
        21: [{"verse": 15, "text": "Lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs."},
             {"verse": 22, "text": "If I will that he tarry till I come, what is that to thee? follow thou me."}]
    },
    "Acts": {
        1: [{"verse": 8, "text": "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth."}],
        2: [{"verse": 4, "text": "And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance."},
            {"verse": 38, "text": "Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost."},
            {"verse": 42, "text": "And they continued stedfastly in the apostles' doctrine and fellowship, and in breaking of bread, and in prayers."}],
        3: [{"verse": 6, "text": "Silver and gold have I none; but such as I have give I thee: In the name of Jesus Christ of Nazareth rise up and walk."},
            {"verse": 19, "text": "Repent ye therefore, and be converted, that your sins may be blotted out."}],
        4: [{"verse": 12, "text": "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved."},
            {"verse": 31, "text": "And when they had prayed, the place was shaken where they were assembled together; and they were all filled with the Holy Ghost."}],
        5: [{"verse": 29, "text": "We ought to obey God rather than men."},
            {"verse": 42, "text": "And daily in the temple, and in every house, they ceased not to teach and preach Jesus Christ."}],
        6: [{"verse": 4, "text": "But we will give ourselves continually to prayer, and to the ministry of the word."}],
        7: [{"verse": 56, "text": "I see the heavens opened, and the Son of man standing on the right hand of God."}],
        8: [{"verse": 4, "text": "Therefore they that were scattered abroad went every where preaching the word."}],
        9: [{"verse": 15, "text": "He is a chosen vessel unto me, to bear my name before the Gentiles, and kings, and the children of Israel."},
            {"verse": 20, "text": "And straightway he preached Christ in the synagogues, that he is the Son of God."}],
        10: [{"verse": 34, "text": "Of a truth I perceive that God is no respecter of persons."},
             {"verse": 43, "text": "Whosoever believeth in him shall receive remission of sins."}],
        11: [{"verse": 18, "text": "Then hath God also to the Gentiles granted repentance unto life."}],
        12: [{"verse": 7, "text": "And, behold, the angel of the Lord came upon him, and a light shined in the prison."}],
        13: [{"verse": 38, "text": "Through this man is preached unto you the forgiveness of sins."},
             {"verse": 47, "text": "I have set thee to be a light of the Gentiles, that thou shouldest be for salvation unto the ends of the earth."}],
        14: [{"verse": 22, "text": "We must through much tribulation enter into the kingdom of God."}],
        15: [{"verse": 11, "text": "But we believe that through the grace of the Lord Jesus Christ we shall be saved."}],
        16: [{"verse": 25, "text": "And at midnight Paul and Silas prayed, and sang praises unto God."},
             {"verse": 31, "text": "Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house."}],
        17: [{"verse": 28, "text": "For in him we live, and move, and have our being."}],
        18: [{"verse": 9, "text": "Be not afraid, but speak, and hold not thy peace."}],
        19: [{"verse": 20, "text": "So mightily grew the word of God and prevailed."}],
        20: [{"verse": 24, "text": "But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy."},
             {"verse": 35, "text": "It is more blessed to give than to receive."}],
        21: [{"verse": 13, "text": "I am ready not to be bound only, but also to die at Jerusalem for the name of the Lord Jesus."}],
        22: [{"verse": 15, "text": "For thou shalt be his witness unto all men of what thou hast seen and heard."}],
        23: [{"verse": 11, "text": "Be of good cheer, Paul: for as thou hast testified of me in Jerusalem, so must thou bear witness also at Rome."}],
        24: [{"verse": 16, "text": "And herein do I exercise myself, to have always a conscience void of offence toward God, and toward men."}],
        25: [{"verse": 11, "text": "If there be none of these things whereof these accuse me, no man may deliver me unto them. I appeal unto Caesar."}],
        26: [{"verse": 18, "text": "To open their eyes, and to turn them from darkness to light, and from the power of Satan unto God."},
             {"verse": 28, "text": "Almost thou persuadest me to be a Christian."}],
        27: [{"verse": 25, "text": "Wherefore, sirs, be of good cheer: for I believe God, that it shall be even as it was told me."}],
        28: [{"verse": 31, "text": "Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him."}]
    },
    "Romans": {
        1: [{"verse": 16, "text": "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth."},
            {"verse": 17, "text": "For therein is the righteousness of God revealed from faith to faith: as it is written, The just shall live by faith."}],
        2: [{"verse": 4, "text": "Or despisest thou the riches of his goodness and forbearance and longsuffering; not knowing that the goodness of God leadeth thee to repentance?"}],
        3: [{"verse": 23, "text": "For all have sinned, and come short of the glory of God."},
            {"verse": 24, "text": "Being justified freely by his grace through the redemption that is in Christ Jesus."}],
        4: [{"verse": 5, "text": "But to him that worketh not, but believeth on him that justifieth the ungodly, his faith is counted for righteousness."}],
        5: [{"verse": 1, "text": "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ."},
            {"verse": 8, "text": "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us."}],
        6: [{"verse": 4, "text": "Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life."},
            {"verse": 23, "text": "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord."}],
        7: [{"verse": 24, "text": "O wretched man that I am! who shall deliver me from the body of this death?"},
            {"verse": 25, "text": "I thank God through Jesus Christ our Lord."}],
        8: [{"verse": 1, "text": "There is therefore now no condemnation to them which are in Christ Jesus."},
            {"verse": 18, "text": "For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us."},
            {"verse": 28, "text": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose."},
            {"verse": 31, "text": "What shall we then say to these things? If God be for us, who can be against us?"},
            {"verse": 37, "text": "Nay, in all these things we are more than conquerors through him that loved us."},
            {"verse": 38, "text": "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,"},
            {"verse": 39, "text": "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."}],
        9: [{"verse": 16, "text": "So then it is not of him that willeth, nor of him that runneth, but of God that sheweth mercy."}],
        10: [{"verse": 9, "text": "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved."},
             {"verse": 10, "text": "For with the heart man believeth unto righteousness; and with the mouth confession is made unto salvation."},
             {"verse": 13, "text": "For whosoever shall call upon the name of the Lord shall be saved."},
             {"verse": 17, "text": "So then faith cometh by hearing, and hearing by the word of God."}],
        11: [{"verse": 33, "text": "O the depth of the riches both of the wisdom and knowledge of God!"},
             {"verse": 36, "text": "For of him, and through him, and to him, are all things: to whom be glory for ever. Amen."}],
        12: [{"verse": 1, "text": "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service."},
             {"verse": 2, "text": "And be not conformed to this world: but be ye transformed by the renewing of your mind."},
             {"verse": 12, "text": "Rejoicing in hope; patient in tribulation; continuing instant in prayer."},
             {"verse": 21, "text": "Be not overcome of evil, but overcome evil with good."}],
        13: [{"verse": 8, "text": "Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law."},
             {"verse": 10, "text": "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law."}],
        14: [{"verse": 8, "text": "For whether we live, we live unto the Lord; and whether we die, we die unto the Lord: whether we live therefore, or die, we are the Lord's."}],
        15: [{"verse": 4, "text": "For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope."},
             {"verse": 13, "text": "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost."}],
        16: [{"verse": 19, "text": "For your obedience is come abroad unto all men. I am glad therefore on your behalf: but yet I would have you wise unto that which is good, and simple concerning evil."},
             {"verse": 27, "text": "To God only wise, be glory through Jesus Christ for ever. Amen."}]
    },
    "1 Corinthians": {
        1: [{"verse": 18, "text": "For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God."},
            {"verse": 25, "text": "Because the foolishness of God is wiser than men; and the weakness of God is stronger than men."}],
        2: [{"verse": 9, "text": "Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him."}],
        3: [{"verse": 16, "text": "Know ye not that ye are the temple of God, and that the Spirit of God dwelleth in you?"}],
        4: [{"verse": 20, "text": "For the kingdom of God is not in word, but in power."}],
        5: [{"verse": 7, "text": "Purge out therefore the old leaven, that ye may be a new lump, as ye are unleavened. For even Christ our passover is sacrificed for us."}],
        6: [{"verse": 19, "text": "What? know ye not that your body is the temple of the Holy Ghost which is in you, which ye have of God, and ye are not your own?"},
            {"verse": 20, "text": "For ye are bought with a price: therefore glorify God in your body, and in your spirit, which are God's."}],
        7: [{"verse": 31, "text": "For the fashion of this world passeth away."}],
        8: [{"verse": 6, "text": "But to us there is but one God, the Father, of whom are all things, and we in him; and one Lord Jesus Christ, by whom are all things, and we by him."}],
        9: [{"verse": 24, "text": "So run, that ye may obtain."},
            {"verse": 27, "text": "But I keep under my body, and bring it into subjection."}],
        10: [{"verse": 13, "text": "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it."},
             {"verse": 31, "text": "Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God."}],
        11: [{"verse": 24, "text": "Take, eat: this is my body, which is broken for you: this do in remembrance of me."},
             {"verse": 25, "text": "This cup is the new testament in my blood: this do ye, as oft as ye drink it, in remembrance of me."}],
        12: [{"verse": 13, "text": "For by one Spirit are we all baptized into one body."},
             {"verse": 27, "text": "Now ye are the body of Christ, and members in particular."}],
        13: [{"verse": 4, "text": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up."},
             {"verse": 8, "text": "Charity never faileth."},
             {"verse": 13, "text": "And now abideth faith, hope, charity, these three; but the greatest of these is charity."}],
        14: [{"verse": 40, "text": "Let all things be done decently and in order."}],
        15: [{"verse": 3, "text": "For I delivered unto you first of all that which I also received, how that Christ died for our sins according to the scriptures."},
             {"verse": 4, "text": "And that he was buried, and that he rose again the third day according to the scriptures."},
             {"verse": 55, "text": "O death, where is thy sting? O grave, where is thy victory?"},
             {"verse": 57, "text": "But thanks be to God, which giveth us the victory through our Lord Jesus Christ."},
             {"verse": 58, "text": "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord."}],
        16: [{"verse": 13, "text": "Watch ye, stand fast in the faith, quit you like men, be strong."},
             {"verse": 14, "text": "Let all your things be done with charity."}]
    },
    "2 Corinthians": {
        1: [{"verse": 3, "text": "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort."},
            {"verse": 4, "text": "Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble."}],
        2: [{"verse": 14, "text": "Now thanks be unto God, which always causeth us to triumph in Christ."}],
        3: [{"verse": 17, "text": "Now the Lord is that Spirit: and where the Spirit of the Lord is, there is liberty."},
            {"verse": 18, "text": "But we all, with open face beholding as in a glass the glory of the Lord, are changed into the same image from glory to glory."}],
        4: [{"verse": 7, "text": "But we have this treasure in earthen vessels, that the excellency of the power may be of God, and not of us."},
            {"verse": 17, "text": "For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory."},
            {"verse": 18, "text": "While we look not at the things which are seen, but at the things which are not seen: for the things which are seen are temporal; but the things which are not seen are eternal."}],
        5: [{"verse": 7, "text": "For we walk by faith, not by sight."},
            {"verse": 17, "text": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."},
            {"verse": 21, "text": "For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him."}],
        6: [{"verse": 2, "text": "Behold, now is the accepted time; behold, now is the day of salvation."}],
        7: [{"verse": 10, "text": "For godly sorrow worketh repentance to salvation not to be repented of."}],
        8: [{"verse": 9, "text": "For ye know the grace of our Lord Jesus Christ, that, though he was rich, yet for your sakes he became poor, that ye through his poverty might be rich."}],
        9: [{"verse": 6, "text": "He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully."},
            {"verse": 7, "text": "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver."},
            {"verse": 8, "text": "And God is able to make all grace abound toward you."}],
        10: [{"verse": 5, "text": "Casting down imaginations, and every high thing that exalteth itself against the knowledge of God."}],
        11: [{"verse": 30, "text": "If I must needs glory, I will glory of the things which concern mine infirmities."}],
        12: [{"verse": 9, "text": "My grace is sufficient for thee: for my strength is made perfect in weakness."},
             {"verse": 10, "text": "Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ's sake: for when I am weak, then am I strong."}],
        13: [{"verse": 11, "text": "Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace; and the God of love and peace shall be with you."},
             {"verse": 14, "text": "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen."}]
    },
    "Galatians": {
        1: [{"verse": 10, "text": "For do I now persuade men, or God? or do I seek to please men? for if I yet pleased men, I should not be the servant of Christ."}],
        2: [{"verse": 20, "text": "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me."}],
        3: [{"verse": 26, "text": "For ye are all the children of God by faith in Christ Jesus."},
            {"verse": 28, "text": "There is neither Jew nor Greek, there is neither bond nor free, there is neither male nor female: for ye are all one in Christ Jesus."}],
        4: [{"verse": 4, "text": "But when the fulness of the time was come, God sent forth his Son, made of a woman, made under the law."},
            {"verse": 6, "text": "And because ye are sons, God hath sent forth the Spirit of his Son into your hearts, crying, Abba, Father."},
            {"verse": 7, "text": "Wherefore thou art no more a servant, but a son; and if a son, then an heir of God through Christ."}],
        5: [{"verse": 1, "text": "Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage."},
            {"verse": 22, "text": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,"},
            {"verse": 23, "text": "Meekness, temperance: against such there is no law."},
            {"verse": 25, "text": "If we live in the Spirit, let us also walk in the Spirit."}],
        6: [{"verse": 2, "text": "Bear ye one another's burdens, and so fulfil the law of Christ."},
            {"verse": 7, "text": "Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap."},
            {"verse": 9, "text": "And let us not be weary in well doing: for in due season we shall reap, if we faint not."},
            {"verse": 14, "text": "But God forbid that I should glory, save in the cross of our Lord Jesus Christ."}]
    },
    "1 Thessalonians": {
        1: [{"verse": 3, "text": "Remembering without ceasing your work of faith, and labour of love, and patience of hope in our Lord Jesus Christ."}],
        2: [{"verse": 13, "text": "For this cause also thank we God without ceasing, because, when ye received the word of God which ye heard of us, ye received it not as the word of men, but as it is in truth, the word of God."}],
        3: [{"verse": 12, "text": "And the Lord make you to increase and abound in love one toward another, and toward all men."}],
        4: [{"verse": 13, "text": "But I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which have no hope."},
            {"verse": 16, "text": "For the Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first."},
            {"verse": 17, "text": "Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord."}],
        5: [{"verse": 16, "text": "Rejoice evermore."},
            {"verse": 17, "text": "Pray without ceasing."},
            {"verse": 18, "text": "In every thing give thanks: for this is the will of God in Christ Jesus concerning you."},
            {"verse": 23, "text": "And the very God of peace sanctify you wholly; and I pray God your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ."}]
    },
    "1 Timothy": {
        1: [{"verse": 15, "text": "This is a faithful saying, and worthy of all acceptation, that Christ Jesus came into the world to save sinners; of whom I am chief."},
            {"verse": 17, "text": "Now unto the King eternal, immortal, invisible, the only wise God, be honour and glory for ever and ever. Amen."}],
        2: [{"verse": 1, "text": "I exhort therefore, that, first of all, supplications, prayers, intercessions, and giving of thanks, be made for all men."},
            {"verse": 5, "text": "For there is one God, and one mediator between God and men, the man Christ Jesus."},
            {"verse": 6, "text": "Who gave himself a ransom for all, to be testified in due time."}],
        3: [{"verse": 15, "text": "But if I tarry long, that thou mayest know how thou oughtest to behave thyself in the house of God, which is the church of the living God, the pillar and ground of the truth."},
            {"verse": 16, "text": "And without controversy great is the mystery of godliness: God was manifest in the flesh, justified in the Spirit, seen of angels, preached unto the Gentiles, believed on in the world, received up into glory."}],
        4: [{"verse": 8, "text": "For bodily exercise profiteth little: but godliness is profitable unto all things, having promise of the life that now is, and of that which is to come."},
            {"verse": 12, "text": "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity."}],
        5: [{"verse": 8, "text": "But if any provide not for his own, and specially for those of his own house, he hath denied the faith, and is worse than an infidel."}],
        6: [{"verse": 6, "text": "But godliness with contentment is great gain."},
            {"verse": 7, "text": "For we brought nothing into this world, and it is certain we can carry nothing out."},
            {"verse": 10, "text": "For the love of money is the root of all evil."},
            {"verse": 12, "text": "Fight the good fight of faith, lay hold on eternal life."}]
    },
    "Hebrews": {
        1: [{"verse": 1, "text": "God, who at sundry times and in divers manners spake in time past unto the fathers by the prophets."},
            {"verse": 2, "text": "Hath in these last days spoken unto us by his Son, whom he hath appointed heir of all things, by whom also he made the worlds."},
            {"verse": 3, "text": "Who being the brightness of his glory, and the express image of his person."}],
        2: [{"verse": 9, "text": "But we see Jesus, who was made a little lower than the angels for the suffering of death, crowned with glory and honour."},
            {"verse": 18, "text": "For in that he himself hath suffered being tempted, he is able to succour them that are tempted."}],
        3: [{"verse": 6, "text": "But Christ as a son over his own house; whose house are we, if we hold fast the confidence and the rejoicing of the hope firm unto the end."}],
        4: [{"verse": 12, "text": "For the word of God is quick, and powerful, and sharper than any twoedged sword."},
            {"verse": 15, "text": "For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin."},
            {"verse": 16, "text": "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need."}],
        5: [{"verse": 8, "text": "Though he were a Son, yet learned he obedience by the things which he suffered."},
            {"verse": 9, "text": "And being made perfect, he became the author of eternal salvation unto all them that obey him."}],
        6: [{"verse": 10, "text": "For God is not unrighteous to forget your work and labour of love."},
            {"verse": 19, "text": "Which hope we have as an anchor of the soul, both sure and stedfast."}],
        7: [{"verse": 25, "text": "Wherefore he is able also to save them to the uttermost that come unto God by him, seeing he ever liveth to make intercession for them."}],
        8: [{"verse": 10, "text": "For this is the covenant that I will make with the house of Israel after those days, saith the Lord; I will put my laws into their mind, and write them in their hearts: and I will be to them a God, and they shall be to me a people."}],
        9: [{"verse": 14, "text": "How much more shall the blood of Christ, who through the eternal Spirit offered himself without spot to God, purge your conscience from dead works to serve the living God?"}],
        10: [{"verse": 23, "text": "Let us hold fast the profession of our faith without wavering; for he is faithful that promised."},
             {"verse": 24, "text": "And let us consider one another to provoke unto love and to good works."},
             {"verse": 25, "text": "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another."}],
        11: [{"verse": 1, "text": "Now faith is the substance of things hoped for, the evidence of things not seen."},
             {"verse": 6, "text": "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him."}],
        12: [{"verse": 1, "text": "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us."},
             {"verse": 2, "text": "Looking unto Jesus the author and finisher of our faith."},
             {"verse": 6, "text": "For whom the Lord loveth he chasteneth, and scourgeth every son whom he receiveth."},
             {"verse": 14, "text": "Follow peace with all men, and holiness, without which no man shall see the Lord."}],
        13: [{"verse": 5, "text": "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee."},
             {"verse": 6, "text": "So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me."},
             {"verse": 8, "text": "Jesus Christ the same yesterday, and to day, and for ever."}]
    }
}

# Additional Old Testament books
ADDITIONAL_OT = {
    "Isaiah": {
        1: [{"verse": 18, "text": "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow."}],
        2: [{"verse": 4, "text": "And he shall judge among the nations, and shall rebuke many people: and they shall beat their swords into plowshares."}],
        3: [{"verse": 10, "text": "Say ye to the righteous, that it shall be well with him: for they shall eat the fruit of their doings."}],
        4: [{"verse": 2, "text": "In that day shall the branch of the LORD be beautiful and glorious."}],
        5: [{"verse": 16, "text": "But the LORD of hosts shall be exalted in judgment, and God that is holy shall be sanctified in righteousness."}],
        6: [{"verse": 3, "text": "And one cried unto another, and said, Holy, holy, holy, is the LORD of hosts: the whole earth is full of his glory."},
            {"verse": 8, "text": "Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me."}],
        7: [{"verse": 14, "text": "Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel."}],
        8: [{"verse": 10, "text": "Take counsel together, and it shall come to nought; speak the word, and it shall not stand: for God is with us."}],
        9: [{"verse": 6, "text": "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace."},
            {"verse": 7, "text": "Of the increase of his government and peace there shall be no end."}],
        10: [{"verse": 27, "text": "And it shall come to pass in that day, that his burden shall be taken away from off thy shoulder."}],
        11: [{"verse": 1, "text": "And there shall come forth a rod out of the stem of Jesse, and a Branch shall grow out of his roots."},
             {"verse": 2, "text": "And the spirit of the LORD shall rest upon him, the spirit of wisdom and understanding, the spirit of counsel and might, the spirit of knowledge and of the fear of the LORD."}],
        12: [{"verse": 2, "text": "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song."}],
        25: [{"verse": 1, "text": "O LORD, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things."},
             {"verse": 8, "text": "He will swallow up death in victory; and the Lord GOD will wipe away tears from off all faces."}],
        26: [{"verse": 3, "text": "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee."},
             {"verse": 4, "text": "Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength."}],
        40: [{"verse": 3, "text": "The voice of him that crieth in the wilderness, Prepare ye the way of the LORD."},
             {"verse": 8, "text": "The grass withereth, the flower fadeth: but the word of our God shall stand for ever."},
             {"verse": 28, "text": "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary?"},
             {"verse": 29, "text": "He giveth power to the faint; and to them that have no might he increaseth strength."},
             {"verse": 31, "text": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."}],
        41: [{"verse": 10, "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."},
             {"verse": 13, "text": "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee."}],
        43: [{"verse": 1, "text": "Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine."},
             {"verse": 2, "text": "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee."},
             {"verse": 18, "text": "Remember ye not the former things, neither consider the things of old."},
             {"verse": 19, "text": "Behold, I will do a new thing; now it shall spring forth; shall ye not know it?"}],
        44: [{"verse": 3, "text": "For I will pour water upon him that is thirsty, and floods upon the dry ground."}],
        45: [{"verse": 22, "text": "Look unto me, and be ye saved, all the ends of the earth: for I am God, and there is none else."}],
        46: [{"verse": 4, "text": "And even to your old age I am he; and even to hoar hairs will I carry you: I have made, and I will bear; even I will carry, and will deliver you."}],
        48: [{"verse": 17, "text": "I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go."}],
        49: [{"verse": 15, "text": "Can a woman forget her sucking child, that she should not have compassion on the son of her womb? yea, they may forget, yet will I not forget thee."},
             {"verse": 16, "text": "Behold, I have graven thee upon the palms of my hands."}],
        50: [{"verse": 7, "text": "For the Lord GOD will help me; therefore shall I not be confounded."}],
        51: [{"verse": 11, "text": "Therefore the redeemed of the LORD shall return, and come with singing unto Zion."}],
        52: [{"verse": 7, "text": "How beautiful upon the mountains are the feet of him that bringeth good tidings, that publisheth peace."}],
        53: [{"verse": 3, "text": "He is despised and rejected of men; a man of sorrows, and acquainted with grief."},
             {"verse": 4, "text": "Surely he hath borne our griefs, and carried our sorrows."},
             {"verse": 5, "text": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."},
             {"verse": 6, "text": "All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all."}],
        54: [{"verse": 10, "text": "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee."},
             {"verse": 17, "text": "No weapon that is formed against thee shall prosper."}],
        55: [{"verse": 6, "text": "Seek ye the LORD while he may be found, call ye upon him while he is near."},
             {"verse": 8, "text": "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD."},
             {"verse": 9, "text": "For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts."},
             {"verse": 11, "text": "So shall my word be that goeth forth out of my mouth: it shall not return unto me void."}],
        57: [{"verse": 15, "text": "For thus saith the high and lofty One that inhabiteth eternity, whose name is Holy; I dwell in the high and holy place, with him also that is of a contrite and humble spirit."}],
        58: [{"verse": 11, "text": "And the LORD shall guide thee continually, and satisfy thy soul in drought."}],
        59: [{"verse": 1, "text": "Behold, the LORD'S hand is not shortened, that it cannot save; neither his ear heavy, that it cannot hear."}],
        60: [{"verse": 1, "text": "Arise, shine; for thy light is come, and the glory of the LORD is risen upon thee."}],
        61: [{"verse": 1, "text": "The Spirit of the Lord GOD is upon me; because the LORD hath anointed me to preach good tidings unto the meek."},
             {"verse": 3, "text": "To give unto them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness."}],
        64: [{"verse": 4, "text": "For since the beginning of the world men have not heard, nor perceived by the ear, neither hath the eye seen, O God, beside thee."},
             {"verse": 8, "text": "But now, O LORD, thou art our father; we are the clay, and thou our potter; and we all are the work of thy hand."}],
        65: [{"verse": 17, "text": "For, behold, I create new heavens and a new earth: and the former shall not be remembered, nor come into mind."},
             {"verse": 24, "text": "And it shall come to pass, that before they call, I will answer; and while they are yet speaking, I will hear."}],
        66: [{"verse": 2, "text": "For all those things hath mine hand made, and all those things have been, saith the LORD: but to this man will I look, even to him that is poor and of a contrite spirit, and trembleth at my word."},
             {"verse": 13, "text": "As one whom his mother comforteth, so will I comfort you."}]
    },
    "Jeremiah": {
        1: [{"verse": 5, "text": "Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee."},
            {"verse": 8, "text": "Be not afraid of their faces: for I am with thee to deliver thee, saith the LORD."}],
        2: [{"verse": 13, "text": "For my people have committed two evils; they have forsaken me the fountain of living waters, and hewed them out cisterns, broken cisterns, that can hold no water."}],
        3: [{"verse": 12, "text": "Return, thou backsliding Israel, saith the LORD; and I will not cause mine anger to fall upon you: for I am merciful."}],
        6: [{"verse": 16, "text": "Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls."}],
        9: [{"verse": 23, "text": "Let not the wise man glory in his wisdom, neither let the mighty man glory in his might, let not the rich man glory in his riches."},
            {"verse": 24, "text": "But let him that glorieth glory in this, that he understandeth and knoweth me, that I am the LORD which exercise lovingkindness, judgment, and righteousness."}],
        10: [{"verse": 6, "text": "Forasmuch as there is none like unto thee, O LORD; thou art great, and thy name is great in might."},
             {"verse": 23, "text": "O LORD, I know that the way of man is not in himself: it is not in man that walketh to direct his steps."}],
        17: [{"verse": 7, "text": "Blessed is the man that trusteth in the LORD, and whose hope the LORD is."},
             {"verse": 8, "text": "For he shall be as a tree planted by the waters, and that spreadeth out her roots by the river."}],
        29: [{"verse": 11, "text": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."},
             {"verse": 12, "text": "Then shall ye call upon me, and ye shall go and pray unto me, and I will hearken unto you."},
             {"verse": 13, "text": "And ye shall seek me, and find me, when ye shall search for me with all your heart."}],
        31: [{"verse": 3, "text": "The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee."},
             {"verse": 33, "text": "But this shall be the covenant that I will make with the house of Israel; After those days, saith the LORD, I will put my law in their inward parts, and write it in their hearts; and will be their God, and they shall be my people."}],
        32: [{"verse": 17, "text": "Ah Lord GOD! behold, thou hast made the heaven and the earth by thy great power and stretched out arm, and there is nothing too hard for thee."},
             {"verse": 27, "text": "Behold, I am the LORD, the God of all flesh: is there any thing too hard for me?"}],
        33: [{"verse": 3, "text": "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not."}]
    },
    "Ezekiel": {
        3: [{"verse": 17, "text": "Son of man, I have made thee a watchman unto the house of Israel: therefore hear the word at my mouth, and give them warning from me."}],
        11: [{"verse": 19, "text": "And I will give them one heart, and I will put a new spirit within you."}],
        18: [{"verse": 23, "text": "Have I any pleasure at all that the wicked should die? saith the Lord GOD: and not that he should return from his ways, and live?"},
             {"verse": 32, "text": "For I have no pleasure in the death of him that dieth, saith the Lord GOD: wherefore turn yourselves, and live ye."}],
        33: [{"verse": 11, "text": "Say unto them, As I live, saith the Lord GOD, I have no pleasure in the death of the wicked; but that the wicked turn from his way and live."}],
        34: [{"verse": 11, "text": "For thus saith the Lord GOD; Behold, I, even I, will both search my sheep, and seek them out."},
             {"verse": 26, "text": "And I will make them and the places round about my hill a blessing; and I will cause the shower to come down in his season; there shall be showers of blessing."}],
        36: [{"verse": 26, "text": "A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh."},
             {"verse": 27, "text": "And I will put my spirit within you, and cause you to walk in my statutes."}],
        37: [{"verse": 5, "text": "Thus saith the Lord GOD unto these bones; Behold, I will cause breath to enter into you, and ye shall live."},
             {"verse": 14, "text": "And shall put my spirit in you, and ye shall live, and I shall place you in your own land: then shall ye know that I the LORD have spoken it, and performed it."}],
        47: [{"verse": 9, "text": "And it shall come to pass, that every thing that liveth, which moveth, whithersoever the rivers shall come, shall live."}]
    },
    "Daniel": {
        1: [{"verse": 8, "text": "But Daniel purposed in his heart that he would not defile himself with the portion of the king's meat."}],
        2: [{"verse": 20, "text": "Blessed be the name of God for ever and ever: for wisdom and might are his."},
            {"verse": 21, "text": "And he changeth the times and the seasons: he removeth kings, and setteth up kings: he giveth wisdom unto the wise."},
            {"verse": 44, "text": "And in the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed."}],
        3: [{"verse": 17, "text": "If it be so, our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of thine hand, O king."},
            {"verse": 18, "text": "But if not, be it known unto thee, O king, that we will not serve thy gods, nor worship the golden image which thou hast set up."},
            {"verse": 25, "text": "He answered and said, Lo, I see four men loose, walking in the midst of the fire, and they have no hurt; and the form of the fourth is like the Son of God."}],
        4: [{"verse": 34, "text": "And at the end of the days I Nebuchadnezzar lifted up mine eyes unto heaven, and mine understanding returned unto me, and I blessed the most High."},
            {"verse": 35, "text": "And all the inhabitants of the earth are reputed as nothing: and he doeth according to his will in the army of heaven, and among the inhabitants of the earth."}],
        5: [{"verse": 27, "text": "TEKEL; Thou art weighed in the balances, and art found wanting."}],
        6: [{"verse": 10, "text": "Now when Daniel knew that the writing was signed, he went into his house; and his windows being open in his chamber toward Jerusalem, he kneeled upon his knees three times a day, and prayed, and gave thanks before his God."},
            {"verse": 22, "text": "My God hath sent his angel, and hath shut the lions' mouths, that they have not hurt me."},
            {"verse": 26, "text": "I make a decree, That in every dominion of my kingdom men tremble and fear before the God of Daniel: for he is the living God, and stedfast for ever."}],
        7: [{"verse": 14, "text": "And there was given him dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him: his dominion is an everlasting dominion."}],
        9: [{"verse": 9, "text": "To the Lord our God belong mercies and forgivenesses, though we have rebelled against him."},
            {"verse": 18, "text": "O my God, incline thine ear, and hear; open thine eyes, and behold our desolations."}],
        10: [{"verse": 12, "text": "Fear not, Daniel: for from the first day that thou didst set thine heart to understand, and to chasten thyself before thy God, thy words were heard."},
             {"verse": 19, "text": "And said, O man greatly beloved, fear not: peace be unto thee, be strong, yea, be strong."}],
        11: [{"verse": 32, "text": "But the people that do know their God shall be strong, and do exploits."}],
        12: [{"verse": 2, "text": "And many of them that sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt."},
             {"verse": 3, "text": "And they that be wise shall shine as the brightness of the firmament; and they that turn many to righteousness as the stars for ever and ever."}]
    },
    "Hosea": {
        1: [{"verse": 10, "text": "Yet the number of the children of Israel shall be as the sand of the sea."}],
        2: [{"verse": 19, "text": "And I will betroth thee unto me for ever; yea, I will betroth thee unto me in righteousness, and in judgment, and in lovingkindness, and in mercies."}],
        3: [{"verse": 5, "text": "Afterward shall the children of Israel return, and seek the LORD their God, and David their king."}],
        4: [{"verse": 6, "text": "My people are destroyed for lack of knowledge."}],
        5: [{"verse": 15, "text": "I will go and return to my place, till they acknowledge their offence, and seek my face."}],
        6: [{"verse": 1, "text": "Come, and let us return unto the LORD: for he hath torn, and he will heal us."},
            {"verse": 3, "text": "Then shall we know, if we follow on to know the LORD."},
            {"verse": 6, "text": "For I desired mercy, and not sacrifice; and the knowledge of God more than burnt offerings."}],
        10: [{"verse": 12, "text": "Sow to yourselves in righteousness, reap in mercy; break up your fallow ground: for it is time to seek the LORD."}],
        11: [{"verse": 4, "text": "I drew them with cords of a man, with bands of love."}],
        12: [{"verse": 6, "text": "Therefore turn thou to thy God: keep mercy and judgment, and wait on thy God continually."}],
        14: [{"verse": 1, "text": "O Israel, return unto the LORD thy God; for thou hast fallen by thine iniquity."},
             {"verse": 4, "text": "I will heal their backsliding, I will love them freely: for mine anger is turned away from him."},
             {"verse": 9, "text": "Who is wise, and he shall understand these things? prudent, and he shall know them? for the ways of the LORD are right."}]
    },
    "Amos": {
        3: [{"verse": 3, "text": "Can two walk together, except they be agreed?"}],
        4: [{"verse": 12, "text": "Therefore thus will I do unto thee, O Israel: and because I will do this unto thee, prepare to meet thy God, O Israel."}],
        5: [{"verse": 4, "text": "For thus saith the LORD unto the house of Israel, Seek ye me, and ye shall live."},
            {"verse": 14, "text": "Seek good, and not evil, that ye may live: and so the LORD, the God of hosts, shall be with you."},
            {"verse": 24, "text": "But let judgment run down as waters, and righteousness as a mighty stream."}]
    },
    "Micah": {
        5: [{"verse": 2, "text": "But thou, Bethlehem Ephratah, though thou be little among the thousands of Judah, yet out of thee shall he come forth unto me that is to be ruler in Israel."}],
        6: [{"verse": 8, "text": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"}],
        7: [{"verse": 7, "text": "Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me."},
            {"verse": 18, "text": "Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy."},
            {"verse": 19, "text": "He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea."}]
    },
    "Zechariah": {
        4: [{"verse": 6, "text": "Not by might, nor by power, but by my spirit, saith the LORD of hosts."}],
        8: [{"verse": 16, "text": "These are the things that ye shall do; Speak ye every man the truth to his neighbour."}],
        9: [{"verse": 9, "text": "Rejoice greatly, O daughter of Zion; shout, O daughter of Jerusalem: behold, thy King cometh unto thee: he is just, and having salvation; lowly, and riding upon an ass."}],
        12: [{"verse": 10, "text": "And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications: and they shall look upon me whom they have pierced."}],
        13: [{"verse": 1, "text": "In that day there shall be a fountain opened to the house of David and to the inhabitants of Jerusalem for sin and for uncleanness."}],
        14: [{"verse": 9, "text": "And the LORD shall be king over all the earth: in that day shall there be one LORD, and his name one."}]
    }
}

def update_books():
    output_dir = r"C:\Users\WelCome\AndroidStudioProjects\CPASongs\app\src\main\assets\bible"
    import os
    import json

    all_verses = {**NEW_TESTAMENT_VERSES, **ADDITIONAL_OT}

    for book_name, chapters in all_verses.items():
        # Determine file name
        if book_name.startswith("1 "):
            file_name = "1_" + book_name[2:].lower().replace(" ", "_") + ".json"
        elif book_name.startswith("2 "):
            file_name = "2_" + book_name[2:].lower().replace(" ", "_") + ".json"
        else:
            file_name = book_name.lower().replace(" ", "_") + ".json"

        file_path = os.path.join(output_dir, file_name)

        if not os.path.exists(file_path):
            print(f"File not found: {file_name}")
            continue

        # Read current file
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        # Update chapters with comprehensive verses
        updated_chapters = []
        for chapter_data in data["chapters"]:
            ch_num = chapter_data["chapter"]
            if ch_num in chapters:
                updated_chapters.append({
                    "chapter": ch_num,
                    "verses": chapters[ch_num]
                })
            else:
                updated_chapters.append(chapter_data)

        data["chapters"] = updated_chapters

        # Write back
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False)

        print(f"Updated {book_name}")

if __name__ == "__main__":
    update_books()

